### ISSUE TITLE
Python fused types broken

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1039]
Did anything happen to the Cython files lately? I get weird errors on Windows using Python 3.3:
```
Cythonizing CoolProp\CoolProp.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    bytes
    unicode
    string

ctypedef fused string_or_size_t:
    string_t
   ^
------------------------------------------------------------

CoolProp\AbstractState.pxd:17:4: Cannot fuse a fused type

Error compiling Cython file:
------------------------------------------------------------
...
    unicode
    string

ctypedef fused string_or_size_t:
    string_t
    cython.integral
   ^
------------------------------------------------------------

CoolProp\AbstractState.pxd:18:4: Cannot fuse a fused type

Error compiling Cython file:
------------------------------------------------------------
...
        
    cpdef change_EOS(self, size_t i, string EOS_name):
        """ Change the EOS for one component - wrapper of c++ function :cpapi:`CoolProp::AbstractState::change_EOS` """
        self.thisptr.change_EOS(i, EOS_name)

    cpdef set_binary_interaction_double(self, string_or_size_t arg1, string_or_size_t arg2, string parameter, double val):
         ^
------------------------------------------------------------

CoolProp\AbstractState.pyx:57:10: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(CoolProp.pyx:2:0)
StatListNode.stats[24] = StatListNode(AbstractState.pyx:3:0)
StatListNode.stats[4] = StatListNode(AbstractState.pyx:23:5)
StatListNode.stats[0] = CClassDefNode(AbstractState.pyx:23:5,
    as_name = 'AbstractState',
    class_name = 'AbstractState',
    doc = '\n    This class is a one-to-one python wrapper of the :cpapi:`AbstractState` class\n    ',
    module_name = '',
    visibility = 'private')
CClassDefNode.body = StatListNode(AbstractState.pyx:24:4)
StatListNode.stats[8] = CFuncDefNode(AbstractState.pyx:57:10,
    args = [...]/5,
    doc = ' Set a double precision interaction parameter - wrapper of c++ function :cpapi:`CoolProp::AbstractState::set_binary_interaction_double` ',
    has_fused_arguments = True,
    is_c_class_method = 1,
    modifiers = [...]/0,
    overridable = 1,
    visibility = 'private')
File 'FusedNode.py', line 693, in update_fused_defnode_entry: FusedCFuncDefNode(AbstractState.pyx:57:10,
    fused_compound_types = [...]/1,
    match = "dest_sig[{{dest_sig_idx}}] = '{{specialized_type_name}}'",
    no_match = 'dest_sig[{{dest_sig_idx}}] = None',
    nodes = [...]/0)
File 'FusedNode.py', line 750, in synthesize_defnodes: FusedCFuncDefNode(AbstractState.pyx:57:10,
    fused_compound_types = [...]/1,
    match = "dest_sig[{{dest_sig_idx}}] = '{{specialized_type_name}}'",
    no_match = 'dest_sig[{{dest_sig_idx}}] = None',
    nodes = [...]/0)

Compiler crash traceback from this point on:
  File "C:\Program Files\Miniconda64_27\envs\CoolProp33\lib\site-packages\Cython\Compiler\FusedNode.py", line 750, in synthesize_defnodes
    if isinstance(self.nodes[0], CFuncDefNode):
IndexError: list index out of range
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    ext_modules = cythonize(ext_modules, compiler_directives = cython_directives)
  File "C:\Program Files\Miniconda64_27\envs\CoolProp33\lib\site-packages\Cython\Build\Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "C:\Program Files\Miniconda64_27\envs\CoolProp33\lib\site-packages\Cython\Build\Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: CoolProp\CoolProp.pyx
```

**Comment by jowr** [comment]
I updated Cython, that could also be the problem...

**Comment by ibell** [comment]
What version of cython?  I've been using 0.24 without problems, perhaps it
is a bug on only python 3.3?

**Comment by jowr** [comment]
Well, no idea, but it happened on two machines (both Win64 and Python 3.3 and latest updates from conda). Feel free to close the issue, if you can live with my hotfix in 0ef10ea.

**Comment by ibell** [comment]
Your fix seems fine.  Removes a bit of the clarity, but if it works, fine
by me.  Have you tested it by any chance?

**Comment by jowr** [comment]
Yes, I am working on the GUI stuff with Python 3.3 and PySide and it seems to work.

**Comment by ibell** [comment]
I guess I mean did you try calling the functions that *use* the fused
types.  You might get runtime failure...
