### ISSUE TITLE
TTSE&HEOS and BICUBIC&HEOS fail with fluid 'Air'

### ISSUE THREAD

**Issue by mstripf** [CoolProp/CoolProp#1186]
Using Python, creating an AbstractState object fails when using 'AIR' as fluid:

```
CoolProp.AbstractState('TTSE&HEOS', 'AIR')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 29, in CoolProp.CoolProp.AbstractState.__cinit__ (CoolProp/CoolProp.cpp:9865)
ValueError: Residual function in secant returned invalid number
```

Same is true for 'BICUBIC&HEOS'. 
Both work fine with "Nitrogen" and other refrigerants.

**Comment by ibell** [comment]
Have you tried Air.mix instead of AIR?  That might be a bit more reliable because it uses the complete mixture model as opposed to the pseudo-pure EOS.  

Alternatively, you might need to bump up the minimum pressure of the phase envelope, as in http://www.coolprop.org/dev/coolprop/Cubics-1.py

**Comment by ibell** [comment]
Ok, pseudo-pure fluids are not supported for tabular backends, but I can't figure out a nice way of quitting if one is being used.  For now, just don't do it, and use the predefined mixture instead (replace "AIR" with "Air.mix")

**Comment by mstripf** [comment]
Thanks Ian!
When I use Air.mix, I get the following, when I first call AbstractState:
```
>>> HEOS = CoolProp.AbstractState('TTSE&HEOS', 'Air.mix')
PHSU flash for mixture
pre is inside
post is inside
PHSU flash for mixture
pre is inside
post is inside
... (repeated many many times)
```
Calling the update function results in:
```
>>> HEOS.update(CoolProp.PT_INPUTS, 101325.0, 293.0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 81, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:16429)
  File "CoolProp/AbstractState.pyx", line 83, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:16318)
ValueError: inputs are not in range, p=101325 Pa, T=293 K
```
From my understanding, this should be well within the range:
```
>>> HEOS.pmax()
1744608000.0
>>> HEOS.Tmin()
61.498642000000004
>>> HEOS.Tmax()
2000.0000000000002
```

**Comment by ibell** [comment]
I pushed changes to silence all the stdout...  I'll look into the others as
well. There are major changes afoot in phase equilibrium calculations with
mixtures.

**Comment by ibell** [comment]
Your code should work.  Hopefully I will have a chance to investigate soon...

**Comment by milesabarr** [comment]
@mstripf Did you ever get this working? I am having the same problem here.

**Comment by mstripf** [comment]
No, still not working. Hoping for a fix in one of the next releases.

**Comment by milesabarr** [comment]
In case you are looking for ideas, my plan for a work-around is to build [interp2d](https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.interpolate.interp2d.html) scipy tables for air using HEOS. My guess is that will be a similar performance to using the CoolProp tables with BICUBIC and TTSE.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
