### ISSUE TITLE
Problems with the solver when running a PropertyPlot demo

### ISSUE THREAD

**Issue by LS-JK** [CoolProp/CoolProp#1375]
I tried running a PropertyPlot example from http://coolprop.sourceforge.net/dev/coolprop/python-plotting.html with the nightly build (instructions [here](http://www.coolprop.org/coolprop/wrappers/Python/index.html#python)), but only after I tried the production release 6.1.0:

```Python
import CoolProp
from CoolProp.Plots import PropertyPlot

print('CoolProp ver:%s'%(CoolProp.__version__))

plot = PropertyPlot('R290', 'ph')
plot.calc_isolines()
plot.show()
```

Here is the result:

```
CoolProp ver:6.1.1dev
Traceback (most recent call last):
  File "C:/Users/LS_JK/Desktop/CoolPlot Demo.py", line 6, in <module>
    plot = PropertyPlot('R290', 'ph')
  File "C:\Tools\WinPython-3.5.2.2\python-3.5.2.amd64\lib\site-packages\CoolProp\Plots\Plots.py", line 68, in __init__
    super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
  File "C:\Tools\WinPython-3.5.2.2\python-3.5.2.amd64\lib\site-packages\CoolProp\Plots\Common.py", line 675, in __init__
    Base2DObject.__init__(self, graph_type[1], graph_type[0], state, **kwargs)
  File "C:\Tools\WinPython-3.5.2.2\python-3.5.2.amd64\lib\site-packages\CoolProp\Plots\Common.py", line 330, in __init__
    if state is not None: self.state = state
  File "C:\Tools\WinPython-3.5.2.2\python-3.5.2.amd64\lib\site-packages\CoolProp\Plots\Common.py", line 353, in state
    self._T_small = self.critical_state.keyed_output(CoolProp.iT)*self._small
  File "C:\Tools\WinPython-3.5.2.2\python-3.5.2.amd64\lib\site-packages\CoolProp\Plots\Common.py", line 341, in critical_state
    self._critical_state = get_critical_point(self._state)
  File "C:\Tools\WinPython-3.5.2.2\python-3.5.2.amd64\lib\site-packages\CoolProp\Plots\Common.py", line 45, in get_critical_point
    new_state.update(CoolProp.PT_INPUTS, crit_state.p, crit_state.T)
  File "CoolProp\AbstractState.pyx", line 94, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:20131)
  File "CoolProp\AbstractState.pyx", line 96, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:20023)
ValueError: solver_rho_Tp was unable to find a solution for T=    369.89, p=4.2512e+06, with guess value    3987.45 with error: Householder4 reached maximum number of iterations

Process finished with exit code 1
```

I expected a plot of some sort.

I'm running WinPython 3.5.2.2 on Windows 10, 64-bit.

**Comment by spinnau** [comment]
The same problem occurs with R134a in CoolProp 6.1.0

```python
from CoolProp import CoolProp as CP
from CoolProp.Plots import PropertyPlot

p = PropertyPlot('R134a', 'TS')
```

```
ValueError                                Traceback (most recent call last)
      2 from CoolProp.Plots import PropertyPlot
      3 
----> 4 p = PropertyPlot('R134a', 'TS')
      5 

[...]

/usr/lib/python3.6/site-packages/CoolProp/Plots/Common.py in critical_state(self)
    339     def critical_state(self):
    340         if self._critical_state is None and self._state is not None:
--> 341             self._critical_state = get_critical_point(self._state)
    342         return self._critical_state
    343     @property

/usr/lib/python3.6/site-packages/CoolProp/Plots/Common.py in get_critical_point(state)
     43         try: new_state.specify_phase(CoolProp.iphase_critical_point)
     44         except: pass
---> 45         new_state.update(CoolProp.PT_INPUTS, crit_state.p, crit_state.T)
     46         #new_state.update(CoolProp.DmolarT_INPUTS, crit_state.rhomolar, crit_state.T)
     47         return new_state

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17421)()

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17310)()

ValueError: solver_rho_Tp was unable to find a solution for T=    374.21, p=4.05928e+06, with guess value     3599.4
```

Creating and updating an AbstractState object with critical temperature and pressure works without any problems for R134a:

```python
Tc = CP.PropsSI('Tcrit', 'R134a')
pc = CP.PropsSI('pcrit', 'R134a')

S = CP.AbstractState('HEOS', 'R134a')
S.update(CP.PT_INPUTS, pc, Tc)
``` 

But if additionally the phase is defined (like it is done in the PropertyPlot methods), then an error is raised:

```python
S = CP.AbstractState('HEOS', 'R134a')
S.specify_phase(CP.iphase_critical_point)
S.update(CP.PT_INPUTS, pc, Tc)
``` 

```
ValueError                                Traceback (most recent call last)
      1 S = CP.AbstractState('HEOS', 'R134a')
      2 S.specify_phase(CP.iphase_critical_point)
----> 3 S.update(CP.PT_INPUTS, pc, Tc)

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17421)()

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17310)()

ValueError: solver_rho_Tp was unable to find a solution for T=    374.21, p=4.05928e+06, with guess value     3599.4
```

**Comment by jowr** [comment]
Thank you for reporting this, I changed the title since it seems like this is not related to the plots.

**Comment by spinnau** [comment]
In CoolProp 6.1.0 the calculation at the critical point with specified phase fails for these fluids:

```python
import CoolProp as CP

for fluid in CP.__fluids__:
    try:
        S = CP.AbstractState('HEOS', fluid)        
        S.specify_phase(CP.iphase_critical_point)
        S.update(CP.PT_INPUTS, S.p_critical(), S.T_critical())         
    except:
        print(fluid)
```

```
CycloPropane
MDM
Oxygen
R134a
trans-2-Butene
```

Calculation for some of them also fails without specifying the phase to `iphase_critical_point`.

**Comment by wlamont** [comment]
Using CoolProp 6.1.0, I also run into the same problem when I try to do a property plot of oxygen:
`pd_plot = CPP.PropertyPlot('Oxygen','PD', `unit_system='KSI')
`ValueError: solver_rho_Tp was unable to find a solution for T=   154.581, p=5.043e+006, with guess value    11318.7`

**Comment by LS-JK** [comment]
Is it possible this was fixed?  When I run the same code I originally posted on Dec 16, 2016, now using WinPython 3.7.1.0 and CoolProp version 6.2.1, I get a plot as expected:

![figure_1](https://user-images.githubusercontent.com/21342113/52011555-e90e3a80-249d-11e9-8c91-0732cbb0702f.png)

There are still some warnings like this:
`
C:\Tools\WinPython-3.7.1.0\python-3.7.1.amd64\lib\site-packages\CoolProp\Plots\Common.py:657: UserWarning: An error occurred for inputs 5554182.916463, -1395.183008 with index (241,): unable to solve 1phase PY flash with Tmin=86.0392, Tmax=975 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Smolar [-61.5215 J/mol/K] is below the minimum value of -61.5194289616 J/mol/K
  UserWarning)
`

It's progress, anyhow.  Thanks!

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
