### ISSUE TITLE
Air-Water mixture phase envelope error

### ISSUE THREAD

**Issue by thomasbigfield** [CoolProp/CoolProp#1416]
Hi all,

I'm currently building a thermodynamic model of a liquid jet ejector (using high velocity water as motive fluid to compress air). For this model I use CoolProp to do the EoS calculations.

I'm unsure whether I should use the humid air properties, as (according to CP website) it employs a mixture of dry air and water vapor, whereas in my model I need to calculate a mixture of air and water (also a bit of vapor ;) ). 

Currently I've been trying to get CoolProp to work with this water/air mixture with the following code:

`mixed = 'HEOS::nitrogen[0.4135]&argon[0.0049]&oxygen[0.111]&water[0.4705]'
HEOS = AbstractState("HEOS", "nitrogen&argon&oxygen&water")
HEOS.set_mole_fractions([0.7812, 0.2096, 0.0092, 0.4705])
HEOS.build_phase_envelope('dummy_variable')

PE = HEOS.get_phase_envelope_data()
plt.figure()
plt.plot(PE.T, PE.p, '-')
plt.show()

CP.PropsSI('H', 'T', 288.15, 'P', 101325, mixed)`

The phase plot shows for a mixture of Argon/Oxygen/Water or Nitrogen/Argon/Oxygen. However the combination of Nitrogen and Water in the mixture gives the following error:

`Traceback (most recent call last):
  File "D:/Dropbox/L&R/FPP Master/Thesis/Ejector Code Galanis Sorin/WJE_CP.py", line 74, in <module>
    HEOS.build_phase_envelope('bla')
  File "CoolProp\AbstractState.pyx", line 375, in CoolProp.CoolProp.AbstractState.build_phase_envelope (CoolProp\CoolProp.cpp:28731)
  File "CoolProp\AbstractState.pyx", line 377, in CoolProp.CoolProp.AbstractState.build_phase_envelope (CoolProp\CoolProp.cpp:28669)
ValueError: solver_rho_Tp was unable to find a solution for T=   231.659, p=       100, with guess value    51082.1`

Does anybody have an idea why I get this error and how to avoid this? Should I be using the lower level interface for such a mixture?
This is my first time posting on GitHub, therefore please let me know if I should add more information.

Cheers!

**Comment by ibell** [comment]
Some of these Type III mixtures (like Nitrogen + Water) are nasty, and difficult to model and handle properly.  In these cases, your better bet is to use NIST REFPROP.  CoolProp just can't handle them,  and unless someone comes in and fixes the code, it will stay that way :(

**Comment by thomasbigfield** [comment]
Thank you for your swift reply Ian, I will consider buying REFPROP then 👍 
Good luck with your permanent position at NIST!

**Comment by mzdr88** [comment]
Hi, I had the same problem. Avoid it by setting a minimum pressure and it should work. Add this line (for example with 0.1 bar):
CP.set_config_double(CP.PHASE_ENVELOPE_STARTING_PRESSURE_PA, 1e4)

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
