### ISSUE TITLE
Error with REFPROP

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#1434]
Hello,

I have not idea why I am getting this error with REFPROP

```
File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:43220)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:43002)
  File "CoolProp/CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:41189)
ValueError: PSmolar: [PSFLSH error 247] density iteration for single-phase state did not converge:  [TPRHO error 202] liquid iteration has not converged for T =  333.61 K, P = 0.35918 MPa, rho (last guess) =   9.7572 mol/L, compositions =   1.00000                         : PropsSI("T","S",1794.35547,"P",359180.6893,"REFPROP-R407C")
```

I have tried to call the same condition individually (from terminal: ```PropsSI("T","S",1794.35547,"P",359180.6893,"REFPROP-R407C")```), it works just fine. I got : ```269.0425697758022```

**Comment by ibell** [comment]
Looks like you are using version 4 of CoolProp.  Weird that you get
different results in terminal and in your program.  Can you give more
significant digits at the place it fails?

**Comment by bo3mrh** [comment]
Well,
I am using a semi-empirical compressor model that was originally developed using REFPROP with CoolProp v4 (http://www.sciencedirect.com/science/article/pii/S0140700715003898). But, now the model is updated to work with v6. I have tested it and compare it with the old version for different operating conditions. Everything's work fine in v6 except for this condition (i.e., "S",1794.35547,"P",359180.6893,"REFPROP-R407C") where it fails.

**Comment by TianbiaoHe** [comment]
Hello,
I have got an error when I was trying to use REFPROP. I have installed REPROP in my computer. CoolProp version is 6.1.0
`CP.PropsSI("T","P",101325,"Q",1,"REFPROP::Water")`
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-5dc1644953bd> in <module>()
----> 1 CP.PropsSI("T","P",101325,"Q",1,"REFPROP::Water")

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:41701)()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:41489)()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:39703)()

ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("T","P",101325,"Q",1,"REFPROP::Water")`

**Comment by ibell** [comment]
Sounds like an installation problem for REFPROP.  What version of REFPROP
do you use?  If you have a 64-bit version of python, you will also need a
64-bit version of REFPROP.

**Comment by hurbutun** [comment]
Hi,
I am trying to call refprop from coolprop on lua to calculate the properties of mixtures.
I tested the following example:

local cp = require 'CoolProp'
local h = cp.PropsSI('H','P',101325,'T',293,'REFPROP::ammonia[0.8]&water[0.2]')

which returns to h=nil though if I calculate it directly from refprop I get a value. Any idea why I cannot get any value from coolprop?

**Comment by ibell** [comment]
Are you on linux or OSX?  If so, file names are case sensitive.  It's also
helpful if you provide the error string you get from
get_global_param_string("errstring", buffer)

**Comment by hurbutun** [comment]
I am on Windows (does refprop work on OSX?). I don't think the problem is related to the file name. For other mixtures it works very well, I just have a problem with ammonia-water mixture. I can obtain values if I use lower pressure levels as well but they don't match with what I get from refprop.
I don't know how to get the error string. I can provide it if you explain how to retrieve it in more detail.

**Comment by ibell** [comment]
Try the get_global_param_string("errstring").  Or in lua, you might need to
pass in an output buffer as well.  Probably this is just a failure of a
flash routine in REFPROP, though its odd that the same inputs would work
for you in REFPROP GUI.

P.S. Yes, REFPROP works on OSX, but requires you to build it yourself.

**Comment by wlamont** [comment]
I get a similar error to @TianbiaoHe.  
When I run:
```python
from CoolProp.CoolProp import PropsSI
PropsSI("T","P",101325,"Q",0,"REFPROP::Water")
```
I get 
```
ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: Could not load these fluids: Water : PropsSI("T","P",101325,"Q",0,"REFPROP::Water")```

When I run 
```python
CP.get_global_param_string("REFPROP_version")
```
I get 
```u'9.1' ```

I also have 64 bit version of Python and REFPROP and I am using windows.

**Comment by ibell** [comment]
Try REFPROP::Water.FLD instead of REFPROP::Water ?  There's a slight chance
that might help

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
