### ISSUE TITLE
PsychScript.py get error when runing

### ISSUE THREAD

**Issue by wta12** [CoolProp/CoolProp#1524]
i got error when try to run script PsychScript.py. Seems problems com from Plots.py. How to debug this error ?
Thanks

> Traceback (most recent call last):
  File "psy_script.py", line 155, in <module>
    RHLabels.plot(ax)
  File "psy_script.py", line 73, in plot
    T_K,w,rot = InlineLabel(xv, yv, y=y, axis = ax)
  File "C:\Program Files\Miniconda3\lib\site-packages\CoolProp\Plots\Plots.py", line 350, in InlineLabel
    plot = PropertyPlot("water","TS",figure=fig,axis=axis)
  File "C:\Program Files\Miniconda3\lib\site-packages\CoolProp\Plots\Plots.py", line 68, in __init__
    super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
  File "C:\Program Files\Miniconda3\lib\site-packages\CoolProp\Plots\Common.py", line 670, in __init__
    self.axis   = kwargs.pop('axis', self.figure.add_subplot(111))
AttributeError: 'NoneType' object has no attribute 'add_subplot'

**Comment by thorade** [comment]
also see #1474

**Comment by wta12** [comment]
Thank @thorade . I have updated my questions, please let me know if you have any suggestion.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
