### ISSUE TITLE
problem with PsychScript.py

### ISSUE THREAD

**Issue by dkhazov** [CoolProp/CoolProp#1565]
Tested for both Python 2.7 and Python 3.5

When I tryed to run PsychScript.py I have the following message:

Traceback (most recent call last):
  File "D:\programs1\Anaconda3\Lib\site-packages\CoolProp\Plots\PsychScript.py", line 44, in <module>
    T_K,w,rot = InlineLabel(xv, yv, y=y, axis = ax)
  File "D:\programs1\Anaconda3\lib\site-packages\CoolProp\Plots\Plots.py", line 350, in InlineLabel
    plot = PropertyPlot("water","TS",figure=fig,axis=axis)
  File "D:\programs1\Anaconda3\lib\site-packages\CoolProp\Plots\Plots.py", line 68, in __init__
    super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
  File "D:\programs1\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py", line 670, in __init__
    self.axis   = kwargs.pop('axis', self.figure.add_subplot(111))
AttributeError: 'NoneType' object has no attribute 'add_subplot'

If I added to string #44: "fig=fig" like this:
T_K,w,rot = InlineLabel(xv, yv, y=y, axis = ax, fig=fig)

I have following:

Traceback (most recent call last):
  File "D:\programs1\Anaconda3\Lib\site-packages\CoolProp\Plots\PsychScript.py", line 44, in <module>
    T_K,w,rot = InlineLabel(xv, yv, y=y, axis = ax, fig=fig)
  File "D:\programs1\Anaconda3\lib\site-packages\CoolProp\Plots\Plots.py", line 351, in InlineLabel
    return plot.inline_label(xv,yv,x,y)
  File "D:\programs1\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py", line 1042, in inline_label
    yv = dimy.to_SI(yv)
  File "D:\programs1\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py", line 142, in to_SI
    def to_SI(self, value): return (value-self.add_SI)/self.mul_SI-self.off_SI
TypeError: unsupported operand type(s) for -: 'list' and 'float'

Without inline text everything is ok, but...

**Comment by ibell** [comment]
Confirmed.  @jowr - I think this was caused by changes to the plotting routines.  In particular, the standalone ``InlineLabel`` function was unnecessarily deprecated, which resulted in this failure.  Can you bring back the ``InlineLabel`` function that doesn't require you to use the whole plotting ecosystem?

**Comment by zckwzk** [comment]
i used have the same problem before. 
create inline.py  (this code i get from Coolprop5)
`from __future__ import print_function, absolute_import

import numpy, matplotlib, matplotlib.pyplot, math, re
from scipy.interpolate import interp1d
from scipy import interpolate
from scipy.spatial.kdtree import KDTree


def InlineLabel(xv,yv,x = None, y= None, axis = None, fig = None):

    def ToPixelCoords(xv,yv,axis,fig):
        [Axmin,Axmax]=axis.get_xlim()
        [Aymin,Aymax]=axis.get_ylim()
        DELTAX_axis=Axmax-Axmin
        DELTAY_axis=Aymax-Aymin
        #print (type(DELTAY_axis))
        width=fig.get_figwidth()
        
        height=fig.get_figheight()
        #print (height)
        pos=axis.get_position().get_points()
        [[Fxmin,Fymin],[Fxmax,Fymax]]=pos
        #print (Fymax)
        DELTAX_fig=width*(Fxmax-Fxmin)
        DELTAY_fig=height*(Fymax-Fymin)
        
        #Convert coords to pixels
        x=(xv-Axmin)/DELTAX_axis*DELTAX_fig+Fxmin
        y=(yv-Aymin)/DELTAY_axis*DELTAY_fig+Fymin
        #print (x)
        return x,y

    def ToDataCoords(xv,yv,axis,fig):
        [Axmin,Axmax]=axis.get_xlim()
        [Aymin,Aymax]=axis.get_ylim()
        DELTAX_axis=Axmax-Axmin
        DELTAY_axis=Aymax-Aymin
        width=fig.get_figwidth()
        height=fig.get_figheight()
        pos=axis.get_position().get_points()
        [[Fxmin,Fymin],[Fxmax,Fymax]]=pos
        DELTAX_fig=(Fxmax-Fxmin)*width
        DELTAY_fig=(Fymax-Fymin)*height
        
        #Convert back to measurements
        x=(xv-Fxmin)/DELTAX_fig*DELTAX_axis+Axmin
        y=(yv-Fymin)/DELTAY_fig*DELTAY_axis+Aymin

        return x,y
    #print (len(yv))
    def get_x_y_dydx(xv,yv,x):
        
        """Get x and y coordinates and the linear interpolation derivative"""
        # Old implementation:
        ##Get the rotation angle
        #f = interp1d(xv, yv)
        #y = f(x)
        #h = 0.00001*x
        #dy_dx = (f(x+h)-f(x-h))/(2*h)
        #return x,y,dy_dx
        
        if len(xv)==len(yv)>1: # assure same length
            if len(xv)==len(yv)==2: # only two points
                if numpy.min(xv)<x<numpy.max(xv):
                    dx    = xv[1] - xv[0]
                    dy    = yv[1] - yv[0]
                    dydx  = dy/dx
                    y     = yv[0] + dydx * (x-xv[0])
                    print (x)
                    return x,y,dydx
                else:
                    raise ValueError("Your coordinate has to be between the input values.")
            else:
                limit = 1e-10                    # avoid hitting a point directly
                diff  = numpy.array(xv)-x        # get differences
                index = numpy.argmin(diff*diff)  # nearest neighbour
                if (xv[index]<x<xv[index+1]      # nearest below, positive inclination
                  or xv[index]>x>xv[index+1]):   # nearest above, negative inclination
                    if diff[index]<limit:
                        index = [index-1,index+1]
                    else:
                        index = [index,  index+1]
                elif (xv[index-1]<x<xv[index]    # nearest above, positive inclination
                  or xv[index-1]>x>xv[index]):   # nearest below, negative inclination
                    if diff[index]<limit:
                        index = [index-1,index+1]
                    else:
                        index = [index-1,index]
                xvnew = xv[index]
                yvnew = yv[index]
                return get_x_y_dydx(xvnew,yvnew,x) # Allow for a single recursion
        else:
            raise ValueError("You have to provide the same amount of x- and y-pairs with at least two entries each.")


    if axis is None:
        axis=matplotlib.pyplot.gca()

    if fig is None:
        fig=matplotlib.pyplot.gcf()


    
    if y is None and x is not None:
        trash=0
        (xv,yv)=ToPixelCoords(xv,yv,axis,fig)
        #x is provided but y isn't
        
        (x,trash)=ToPixelCoords(x,trash,axis,fig)

        #Get the rotation angle and y-value
        x,y,dy_dx = get_x_y_dydx(xv,yv,x)
        rot = numpy.arctan(dy_dx)/numpy.pi*180.

    elif x is None and y is not None:
        #y is provided, but x isn't
        
        _xv = xv[::-1]
        _yv = yv[::-1]
        #Find x by interpolation
        x = interp1d(yv, xv)(y)
        #print (x-273.15)
        trash=0
        (xv,yv)=ToPixelCoords(xv,yv,axis,fig)
        (x,trash)=ToPixelCoords(x,trash,axis,fig)

        #Get the rotation angle and y-value
        x,y,dy_dx = get_x_y_dydx(xv,yv,x)
        rot = numpy.arctan(dy_dx)/numpy.pi*180.
    (x,y)=ToDataCoords(x,y,axis,fig)
    return (x,y,rot)
`

import it  to your psychScript.py
 ` from inlinel import * `

and use this code to call the function 
`       T_K,w,rot = InlineLabel(xv, yv, y=y, x = None)`

**Comment by ibell** [comment]
Good point, I know I had that code in there before.  Here is a url to that
old code:
https://www.potterybarn.com/products/riviera-stripe-roman-shade/?catalogId=84&sku=5852744&cm_ven=PLA&cm_cat=Google&cm_pla=Rugs%20%26%20Windows%20%3E%20Roman%20Shades&kwid=productads-adid
^202405455976-device^c-plaid^328117595440-sku^5852744-adType^PLA&gclid=CjwKCAjwhOvPBRBxEiwAx2nhLnb4bw98ZdiyZIY0Hrh-lw55wSOWfm9tGbo4bSbyPallOtZRLYQrbBoCh10QAvD_BwE&cm_ite=[[PLA]%20-%20Overlap%20Desktop]

**Comment by thorade** [comment]
@ibell That was probably the wrong link

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
