### ISSUE TITLE
Java Wrapper and Netbeans

### ISSUE THREAD

**Issue by kitessakennedy** [CoolProp/CoolProp#1615]
I am trying to use the CoolProp Java Wrapper and the Example.
I have created a new Project in Netbeans:
RefpropTest
|-Source Packages
--|-testPackage
----|-Example.java
--|-testpackage.coolProp
----|-AbstractState.java
----|-Configuration.java
...
In each of the CoolProp java files, I added "testPackage.coolProp;" at the beginning.
I also adjusted the following to the Example class:
```
    static {
        System.out.println("java.library.path = " + System.getProperty("java.library.path"));
        System.loadLibrary("CoolProp");
        System.out.println("Cool Prop DLL loaded.");
    }
```

When I run, I get the following:

```
run:
java.library.path = C:\Program Files\Java\jdk1.8.0_141\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\OpenText\Viewer\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\Java\jdk1.7.0_80\bin;C:\Program Files (x86)\Java\jre7\bin;;C:\Users\user\AppData\Roaming\CoolProp;.
Cool Prop DLL loaded.
**************** INFORMATION ***************
This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
Exception in thread "main" java.lang.UnsatisfiedLinkError: testPackage.coolProp.CoolPropJNI.get_global_param_string(Ljava/lang/String;)Ljava/lang/String;
	at testPackage.coolProp.CoolPropJNI.get_global_param_string(Native Method)
	at testPackage.coolProp.CoolProp.get_global_param_string(CoolProp.java:121)
	at testPackage.Example.main(Example.java:29)
C:\Users\user\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 1 second)
```

I have the CoolProp.dll in the SysWOW folder and in the AppData\Roaming folder.
Also, with the message" Cool Prop DLL loaded."  I know it was found.
Why doesn't it recognize the method "get_global_param_string"?
If you can help, I'd appreciate it.  If it's a JNI problem, then I will continue to investigate.  Thanks.

**Update:**
Yes, I have been trying to follow the documentation and make that work as well.  Thank you for your advice.  I will keep working and update when I have more.  Thank you.

**Comment by ibell** [comment]
Can you get this working outside of netbeans according to the documentation?  That is the first thing to check.  Also, you can modify the package directly as part of the cmake call: http://www.coolprop.org/dev/coolprop/wrappers/Java/index.html#build

**Comment by ibell** [comment]
Also, please use code blocks, it makes your issue much more readable: https://guides.github.com/features/mastering-markdown/

**Comment by ibell** [comment]
One of the big mistakes that we made in CoolProp (and that we can't easily undo) is to name the SWIG wrapper DLL the same as the "normal" DLL of CoolProp that exposes the high level interface.  They are fundamentally totally different animals but have the same name.  So probably it loaded the "normal" DLL, which is not the one you wanted, which is why it was missing the SWIG wrapped method.  

As usual, the first thing to do is to clean up, remove all CoolProp.dll from your system (really all of them).  Then:

1. Follow our canonical instructions for building the Java examples.  Make sure that works.
2. Then start experimenting.

Good luck!

**Comment by ibell** [comment]
Bump - any update?

**Comment by JavierTSalas** [comment]
I'm having the same problem.
However CoolProp doesn't even work in cmd so I don't know if I installed it right. So far I've tried the following:

- Using the windows installer (I'm running Win10 64 bit)
- Setting the %PATH% to the folder where the dll is installed
- Using CMake to build (The test are failing but I'm getting warnings and no errors) CoolProp

For CMake I installed the wrapper prerequisites

- git
- Python (3.7) - which needed the module six
- Visual Studio 2017 Community Edition + Various 'Individual Components" for resolving CMake errors
- CMake for windows
- 7z

I've verified that all of the above are working in cmd except for VS2017 which I was able to compile a project.
 
I'm open to any suggestions!

**Comment by ibell** [comment]
I would maybe roll back to Python 3.6, a lot of stuff isn't ready for
Python 3.7 yet (including CoolProp), but I doubt that is the problem.  Can
you please post a complete log of building the Java DLL along with all
commands run at the command line?  Otherwise it's tricky to know what to
look into.

One major design booboo that we made originally was to use the same file
name for the special Java DLL and the conventional CoolProp DLL.  Maybe
that's the source of your problems as well?  They are not the same thing,
although they have the same filename.  Oops.

**Comment by JavierTSalas** [comment]
Sure, for reference this is the command I used to generate the build file:
```bash 
cmake .. -G "Visual Studio 15 2017" -DCOOLPROP_JAVA_MODULE=ON -DBUILD_TESTING=ON -DCOOLPROP_SWIG_OPTIONS="-package org.coolprop"
```

the command for building:
```bash
cmake --build . --config Release
```

here's the output of the build:
``` bash
Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/16/2018 9:36:24 AM.
Project "C:\Users\JavierTSalas\CoolProp\build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Users\JavierTSalas\CoolProp\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\JavierTSalas\CoolProp\
build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
InitializeBuildStatus:
  Creating "Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was spec
  ified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\JavierTSalas\CoolProp\build\ZERO_CHECK.vcxproj" (default targets).

Project "C:\Users\JavierTSalas\CoolProp\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\JavierTSalas\CoolProp\
build\CoolProp.vcxproj" (3) on node 1 (default targets).
Project "C:\Users\JavierTSalas\CoolProp\build\CoolProp.vcxproj" (3) is building "C:\Users\JavierTSalas\CoolProp\b
uild\generate_headers.vcxproj" (4) on node 1 (default targets).
InitializeBuildStatus:
  Creating "Win32\Release\generate_headers\generate_headers.tlog\unsuccessfulbuild" because "AlwaysCrea
  te" was specified.
CustomBuild:
  git version 2.18.0.windows.1
  cpversion.h is up to date
  version written to hidden file: C:\Users\JavierTSalas\CoolProp\.version for use in builders that don't use
   git repo
  git is accessible at the command line
  git revision is 2bbee7fa250b262094b555c667197e1b8283ad28
  gitrevision.h is up to date
  all_fluids_JSON.h is up to date
  all_incompressibles_JSON.h is up to date
  mixture_departure_functions_JSON.h is up to date
  mixture_binary_pairs_JSON.h is up to date
  predefined_mixtures_JSON.h is up to date
  all_cubics_JSON.h is up to date
  cubic_fluids_schema_JSON.h is up to date
FinalizeBuildStatus:
  Deleting file "Win32\Release\generate_headers\generate_headers.tlog\unsuccessfulbuild".
  Touching "Win32\Release\generate_headers\generate_headers.tlog\generate_headers.lastbuildstate".
Done Building Project "C:\Users\JavierTSalas\CoolProp\build\generate_headers.vcxproj" (default targets).

InitializeBuildStatus:
  Touching "CoolProp.dir\Release\CoolProp.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Link:
  All outputs are up-to-date.
  CoolProp.vcxproj -> C:\Users\JavierTSalas\CoolProp\build\Release\CoolProp.dll
PostBuildEvent:
  setlocal
  cd C:\Users\JavierTSalas\CoolProp\build
  if %errorlevel% neq 0 goto :cmEnd
  C:
  if %errorlevel% neq 0 goto :cmEnd
  7z a C:/Users/JavierTSalas/CoolProp/build/platform-independent.7z C:/Users/JavierTSalas/CoolProp/build/*.java -
  x!Example.java
  if %errorlevel% neq 0 goto :cmEnd
  :cmEnd
  endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  :cmErrorLevel
  exit /b %1
  :cmDone
  if %errorlevel% neq 0 goto :VCEnd
  setlocal
  cd C:\Users\JavierTSalas\CoolProp\dev\scripts\examples
  if %errorlevel% neq 0 goto :cmEnd
  C:
  if %errorlevel% neq 0 goto :cmEnd
  python example_generator.py Java C:/Users/JavierTSalas/CoolProp/build/Example.java
  if %errorlevel% neq 0 goto :cmEnd
  :cmEnd
  endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  :cmErrorLevel
  exit /b %1
  :cmDone
  if %errorlevel% neq 0 goto :VCEnd
  :VCEnd

  7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

  Open archive: C:/Users/JavierTSalas/CoolProp/build/platform-independent.7z
  --
  Path = C:/Users/JavierTSalas/CoolProp/build/platform-independent.7z
  Type = 7z
  Physical Size = 13766
  Headers Size = 878
  Method = LZMA2:192k
  Solid = +
  Blocks = 1

  Scanning the drive:
  36 files, 164246 bytes (161 KiB)

  Updating archive: C:/Users/JavierTSalas/CoolProp/build/platform-independent.7z

  Add new data to archive: 36 files, 164246 bytes (161 KiB)


  Files read from disk: 36
  Archive size: 13766 bytes (14 KiB)
  Everything is Ok
  written to C:/Users/JavierTSalas/CoolProp/build/Example.java
FinalizeBuildStatus:
  Deleting file "CoolProp.dir\Release\CoolProp.tlog\unsuccessfulbuild".
  Touching "CoolProp.dir\Release\CoolProp.tlog\CoolProp.lastbuildstate".
Done Building Project "C:\Users\JavierTSalas\CoolProp\build\CoolProp.vcxproj" (default targets).

PrepareForBuild:
  Creating directory "Win32\Release\ALL_BUILD\".
  Creating directory "Win32\Release\ALL_BUILD\ALL_BUILD.tlog\".
InitializeBuildStatus:
  Creating "Win32\Release\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specif
  ied.
FinalizeBuildStatus:
  Deleting file "Win32\Release\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
  Touching "Win32\Release\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
Done Building Project "C:\Users\JavierTSalas\CoolProp\build\ALL_BUILD.vcxproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.40
```

**Comment by ibell** [comment]
How about the shell output?  That is usually much more informative than the
logs.  Why they don't capture that directly I've never been able to
understand.  From reading that log, I don't see an obvious problem.

**Comment by JavierTSalas** [comment]
Sorry for the late reply but that was the output of the shell. I'm no longer having trouble with netbeans loading the DLL in a empty project. However, when I try to load the DLL into my main project I get the following error:
``` bash
java.lang.UnsatisfiedLinkError: CoolProp.CoolPropJNI.Props1SI(Ljava/lang/String;Ljava/lang/String;)D
``` 
The project heavily relies on the swing library, has a couple of open source libraries (jfreechar, jcomon, junit, jamod) and two proprietary libraries.  Do you think it's because swing is managing the threads (I know it's a long shot but I'm just throwing darts at this point)

**Comment by JavierTSalas** [comment]
For the empty project I was using the sourceforge windows 64 bit dll and that was working.  I just tried the dll that I built which is 32 bit and that one worked! I'm assuming I'll have to build this dll on the machine that I want to use it on right? Refprop calls don't seem to work with either dll though.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
