### ISSUE TITLE
Excel and Python wrapper, PropsSI problem with Q as input

### ISSUE THREAD

**Issue by sodynamic** [CoolProp/CoolProp#1619]
I want to try the example about IF97 showed in [http://www.coolprop.org/dev/fluid_properties/IF97.html](url), and there would be an error if I use Q as the input, using Excel or Python.
Here is the operation:
_import CoolProp.CoolProp as CP_
_CP.PropsSI('P','T',500,'Q',0,'IF97::Water')_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:41701)
  File "CoolProp\CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:41489)
  File "CoolProp\CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:39703)
ValueError: bad input_pair : PropsSI("P","T",500,"Q",0,"IF97::Water")

Does this means the CoolProp I have installed is not the one showed in the documentation? I have installed my python package by command "pip install coolprop", and I followed the instructions of mannual installation showed on `http://www.coolprop.org/dev/coolprop/wrappers/Excel/index.html#excel` for Excel wrapper.

Can someone offer me a solution for this problem?

**Comment by ibell** [comment]
You need to use the nightly build, 6.1 doesn't include that capability.

**Comment by ibell** [comment]
The second option in this section: http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation
