### ISSUE TITLE
errors when calculating properties of water at critical pressure

### ISSUE THREAD

**Issue by crteensy** [CoolProp/CoolProp#1678]
For plotting purposes, I'm trying to calculate properties of water at critical pressure. This works fine at the critical point, but not when I move away from it:

```
from CoolProp import AbstractState
import CoolProp.CoolProp as CP

backend="?"
fluid="water"

state = AbstractState(backend, fluid)

pcrit = CP.PropsSI(fluid, "pcrit")

print("critical point")
state.update(CP.PQ_INPUTS, pcrit, 0)

smass = 4000
print("pcrit, smass={}".format(smass))
state.update(CP.PSmass_INPUTS, pcrit, smass)
```
the last line throws an error message:
```
>>> state.update(CP.PSmass_INPUTS, pcrit, 5000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 90, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17930)
  File "CoolProp/AbstractState.pyx", line 92, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17822)
ValueError: Residual function in secant returned invalid number
```
I also tried using PT_INPUTS, starting at minimum temperature for water (273.16 K). AFAIK Water should be liquid at critical pressure and triple point temperature, but CP outputs an empty string for the phase and throws the same error as above. Only when I use a higher temperature (starting between 300 and 350 K), things start to work without errors.

Increasing pressure by just 1 Pa also gets rid of the errors, as in
```
state2.update(CP.PT_INPUTS, pcrit+1, tmin)`
```

Is there a reliable way of evaulating at pcrit over the whole defined range of some other variable (for example entropy or temperature, as above)?

**Comment by henningjp** [comment]
I suspect this is an initial value problem and CP is having trouble determining the phase.

For the PT inputs, the phase is clearly liquid.  Before you call update(), set the phase to liquid and CP has no trouble:
```python
>>> state.specify_phase(CP.iphase_liquid)
>>> state.update(CP.PT_INPUTS, pcrit, Tmin)
>>> state.smass()
0.6054667211540341
```
Using your PSmass inputs @ Smass = 4000, p = pcrit is just to the left of the critical point in the liquid region.  Setting phase to liquid, or even supercritical_liquid doesn't help.  As you noted, going just above or below the critical pressure by 1Pa or even smaller, does not throw the error:
```python
>>> state.unspecify_phase()
>>> state.update(CP.PSmass_INPUTS, pcrit, smass)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\AbstractState.pyx", line 94, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp\AbstractState.pyx", line 96, in CoolProp.CoolProp.AbstractState.update
ValueError: Residual function in secant returned invalid number
>>> state.update(CP.PSmass_INPUTS, pcrit-1, smass)
>>> state.update(CP.PSmass_INPUTS, pcrit+1, smass)
>>> state.update(CP.PSmass_INPUTS, pcrit+0.01, smass)
>>> state.update(CP.PSmass_INPUTS, pcrit-0.01, smass)
```
I suspect this is a bug that occurs when p is exactly pcrit and using PS inputs.  In fact, it appears to happen for any values of smass.
```python
>>> state.update(CP.PSmass_INPUTS, pcrit, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\AbstractState.pyx", line 94, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp\AbstractState.pyx", line 96, in CoolProp.CoolProp.AbstractState.update
ValueError: Residual function in secant returned invalid number
>>> state.update(CP.PSmass_INPUTS, pcrit+0.01, 1)
>>> state.update(CP.PSmass_INPUTS, pcrit-0.01, 1)
```
If you are only interested in water properties, I ran your examples using the IF97 backend ``"IF97::Water"`` for water/steam properties instead of HEOS and it works just fine for both cases.  You'll need the development version, however, to get all input pairs until CP 6.2 is released.  See the [IF97 dev docs](http://www.coolprop.org/dev/fluid_properties/IF97.html).

**Comment by crteensy** [comment]
So I have these options:
1. for plotting purposes, go just slightly above pcrit and plot along that since it won't make a visible difference anyway
2. specify phase and use PT_INPUTS instead of PSmass_INPUTS, manually adapt phase above Tcrit
3. get dev version and use IF97 backend (less portable until 6.2 is released)

I guess it's going to be 1).

**Comment by henningjp** [comment]
@ibell & @jowr This looks to be related to #1611.   Some debugging shows that in ``HelmholtzEOSMixtureBackend::p_phase_determination_pure_or_pseudopure`` when 
_p is potentially on the saturation curve between ptriple and psat_max (pcrit), the ancillaries are used to determine Tsat from _p, then determine phase to the left or right of the saturation curve.  Makes sense.  
```cpp
    // Check between triple point pressure and psat_max
    else if (_p >= components[0].EOS().ptriple*0.9999 && _p <= psat_max)
    {
        // First try the ancillaries, use them to determine the state if you can

        // Calculate dew and bubble temps from the ancillaries (everything needs them)
        _TLanc = components[0].ancillaries.pL.invert(_p);
        _TVanc = components[0].ancillaries.pV.invert(_p);
```
However, if _p == pcrit, the secant method used in the inverse falls off the end of the saturation curve and fails, giving the errors above.  Looks like it's been this way for some time.  I have a fix below that bypasses the ancillaries altogether if _p is exactly at psat_max (pcrit).
```cpp
    // Check between triple point pressure and psat_max
    else if (_p >= components[0].EOS().ptriple*0.9999 && _p <= psat_max)
    {
        // First try the ancillaries, use them to determine the state if you can

        // Calculate dew and bubble temps from the ancillaries (everything needs them)
        if (_p == psat_max) {                                   // However, if we are right at the critical pressure...
            _TLanc = components[0].ancillaries.pL.get_Tmax();   //     Secant method in ancillaries::invert(_p) will fail,
            _TVanc = components[0].ancillaries.pV.get_Tmax();   //     so just set T to Tmax = Tcrit = "tip" of the curve.
        }
        else {                                                  // Otherwise, call the inverse ancillary with no problems
            _TLanc = components[0].ancillaries.pL.invert(_p);
            _TVanc = components[0].ancillaries.pV.invert(_p);
        }
```
This works and fixes the error for not only (p, Smass) inputs, but also (p, Hmass) and (p, Umass) input pairs when p = pcrit.  I don't know what else calls the ancillary invert(_p) function, which would fail for the same reason at pcrit.  Should it be fixed there, at the root cause of the problem, instead?

**Comment by henningjp** [comment]
Looks like Brent() solver fails (probably because the solution point is at the very end of the ancillary curve) but error is caught and the catch code calls Secant().  There are some weird issues with Secant() but it only gets called when Brent fails, which may not be very often, so I'm not going to fix it here.  I'll PR the patch above so that we at least get the p = pcrit calls working in v6.2.0.

**Comment by henningjp** [comment]
This is Pandora's box.  In addition to p = pcrit, there are bands above and below pcrit where secant() fails and can't determine phase.  The bands move depending on the fluid.  Successful update calls to Water are shown below (missing points in the grid are where update failed).  These are plotted on 5 Pa intervals from (pcrit - 100 Pa) to (pcrit + 150 Pa).

![ph errors](https://user-images.githubusercontent.com/17114032/39084185-2a632002-453f-11e8-9a29-ee5644ccfd67.PNG)

Some of this has to do with ill behaved ancillaries very near the critical point.  The saturated enthalpy curve is plotted below from (pcrit - 100) to pcrit.

![enthalpy saturation h2o](https://user-images.githubusercontent.com/17114032/39084207-6b434e58-453f-11e8-9a87-fe2a4d00a608.PNG)

The pseudo-pure fluids are even worse.

Since this is a much bigger issue, I'm pulling this item our of the 6.2.2 milestone, killing PR #1681, but leaving this open for further investigation.

For now, the workaround is to stay away from pcrit ± 100 Pa.

**Comment by henningjp** [comment]
This is an old one that I think has been addressed.  I believe it was fixed by #2250 and #2351 and maybe others since 6.7.1.

Test plots above now look like this in version 7.2.0:

<img width="901" height="870" alt="Image" src="https://github.com/user-attachments/assets/a6f2950b-0746-45fb-bd14-81039cc3d51c" />

And the Saturation Curves plot much nicer near the critical point.

<img width="1009" height="537" alt="Image" src="https://github.com/user-attachments/assets/497bb6bb-1c55-4370-b2ea-307699575c17" />

Closing this issue.
