### ISSUE TITLE
[Python] Manual install of CoolProp after SolutionFluids.py mod makes INCOMP backend unusable

### ISSUE THREAD

**Issue by stephen-young** [CoolProp/CoolProp#1710]
For some context with this issue please see the discussion on the Google group [here](https://groups.google.com/forum/#!topic/coolprop-users/dDWVXRImJlc). 

First of all, I should probably start off by saying that I am trying to do something that would probably not fall under normal use of the software... I am trying to define a custom incompressible fluid for use with a model that I have written in MATLAB (those interested can see my master's thesis about it [here](https://zone.biblio.laurentian.ca/handle/10219/2723) so that effects of using a sodium sulfate solution can be modeled. 

After following the workflow prescribed in the Google group discussion, the install appears to go OK except that when I the following code:
````
import CoolProp.CoolProp as CP
AS = CP.AbstractState("INCOMP", "MNA")
````
I get the following error:
````
Unable to load fluid: DowJ; error was input "[
    -250.0,
    1.5,
    10.0
]" is not a 2D array
input "[
    -250.0,
    1.5,
    10.0
]" is not a 2D array
Traceback (most recent call last):
  File "CoolPropTest.py", line 4, in <module>
    AS = CP.AbstractState("INCOMP", "MNA")
  File "CoolProp\AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: key [MNA] was not found in string_to_index_map in JSONIncompressibleLibrary
````
When I try to use my custom fluid I get a similar error. Attached is a zip file with all the command line output during the CoolProp install and my modified SolutionFluids.py file with my custom fluid definition.

[command_line_output.zip](https://github.com/CoolProp/CoolProp/files/2138842/command_line_output.zip)

[SolutionFluids.zip](https://github.com/CoolProp/CoolProp/files/2138844/SolutionFluids.zip)

Is there something obvious that I am doing wrong here?

**Comment by ibell** [comment]
Could you try to make a pull request with your updated solution (
https://github.com/CoolProp/CoolProp/wiki/Contributing:-git-development-workflow)?
That would help to figure out what has gone wrong and cleanly see the
differences.  Then we could hopefully integrate your changes directly into
CoolProp (and you'd get the credit !)!

Sounds like something interesting has gotten messed up, and this would help
us to figure out what.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
