### ISSUE TITLE
Tabular backend effects range?

### ISSUE THREAD

**Issue by khoopes** [CoolProp/CoolProp#1721]
Hello,

Should the tabular back end change the fluid range?

`import CoolProp
co2 = CoolProp.AbstractState('HEOS', 'CO2')
co2.update(CoolProp.PT_INPUTS, 101325, 300)
print co2.rhomass()

co2 = CoolProp.AbstractState('TTSE&HEOS', 'CO2')
co2.update(CoolProp.PT_INPUTS, 101325*50, 300)
print co2.rhomass()

co2 = CoolProp.AbstractState('TTSE&HEOS', 'CO2')
co2.update(CoolProp.PT_INPUTS, 101325, 300)
print co2.rhomass()
`

produces the following result:
`1.79663609738
131.243106242
Traceback (most recent call last):
  File "C:/Users/khoopes/Desktop/table_test.py", line 11, in <module>
    co2.update(CoolProp.PT_INPUTS, 101325, 300)
  File "CoolProp\AbstractState.pyx", line 90, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:17921)
  File "CoolProp\AbstractState.pyx", line 92, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:17813)
ValueError: inputs are not in range, p=101325 Pa, T=300 K`

Thanks

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
