### ISSUE TITLE
coolprop with php?

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#1771]
i am doing a website, for calc refstatus on web, it is easy to cross-platform，but... 

wapper in github，where is the php demo？

i download a file named libcoolprop.so，from https://sourceforge.net/projects/coolprop/files/CoolProp/6.1.0/PHP/Linux/

got some error，anyone who can help me ?

**Comment by ibell** [comment]
Did you find this page:
http://www.coolprop.org/coolprop/wrappers/PHP/index.html#php ?

**Comment by birdol** [comment]
yes,  i try the method from that page，but after 
i edit php.ini ，add this line
```php
extension = "libCoolProp.so"
```
the phpinfo(); looks like the same，no message for coolprop in phpinfo function

**Comment by birdol** [comment]
which php version it`s depends?   I tried php5.4 and php7.2

**Comment by ibell** [comment]
Did you try 5.4?

**Comment by jfeng08** [comment]
Ian,
We are upgrading PHP from 5.4 to 7.3. The CoolProp is not loaded in PHP 7.3 with both a relative and absolute path in php.ini. Are you going to write the page for PHP 7.3 recently?

**Comment by birdol** [comment]
Please support php7.3.......thank you so much... :)

**Comment by ibell** [comment]
If you upgrade to Swig 4, it seems like PHP7 might be supported: http://www.swig.org/Doc4.0/Php.html#Php .  I don't use PHP so I can't provide any support. CoolProp is a volunteer supported project, so you are welcome to fix it to make it work with PHP 7.

**Comment by jfeng08** [comment]
Ian,
With Ubuntu 18.04 64-bit based server, SWIG 4.0.2, PHP 7.2.25, we got the file CoolProp.so and the php module CoolProp.php generated.

We put CoolProp.so in php extension_dir and it is loaded. The high-level example works, but the low-level call does not work, it complaints about "$r = AbstractState_factory($backend, $fluid_names)" and here is the error message:

PHP Fatal error: Uncaught Exception: You cannot use the REFPROPMixtureBackend. 

Please advise.

**Comment by ibell** [comment]
The easy answer is to not use the REFPROP backend.  The code should
otherwise still be fine, if it uses other backends.

**Comment by jfeng08** [comment]
Ian,
If I use HEOS backend $CO2 = ConcreteState::factory("HEOS", "CO2"), then I got the following error :

**unable to solve 1phase PY flash with Tmin=218.095, Tmax=3000 due to error: p is not a valid number in CoolProp.php:1247
Stack trace:
#0 CoolProp.php(1247): abstractstate_update(Resource id #5, 20, 286248.15104367, 7603085)
#1 xxx.php(543): AbstractState->update(20, 286248.15104367, 7603085)**

My input pair is HmassP_INPUTS

**Comment by ibell** [comment]
Recommend you try those inputs on Python or something like it to make sure
problem is not the inputs.  With enthalpy inputs that is always a
possibility because of reference state

**Comment by jfeng08** [comment]
Ian,
Is HEOS low-level? It takes long time. Any other backends?

**Comment by ibell** [comment]
HEOS is the default backend with the Helmholtz equation of state.  Again, I
recommend you test outside of PHP to remove a potential source of problems

**Comment by jfeng08** [comment]
Ian,
Our CoolProp.so was compiled using PHP 7.2 but it is not loaded in PHP 7.3 although PHP 7.3 is also installed on our server. I am wondering how to specify what php version is used when compiling the library?

**Comment by ibell** [comment]
Probably you need to compile with the same version as you want to use for
binary compatibility.

**Comment by jfeng08** [comment]
We installed both php7.2 and php7.3 on the server. When compiling CoolProp.so, the php7.2 API was selected by default (see below). Is there any way to specify the use of the php7.3 API?

root@denver5:/opt/plesk/php/7.2/bin# /opt/plesk/php/7.3/bin/php -m | grep Cool
PHP Warning: PHP Startup: CoolProp: Unable to initialize module
Module compiled with module API=20170718
PHP compiled with module API=20180731

**Comment by ibell** [comment]
Yes, you should look into alternatives: http://manpages.ubuntu.com/manpages/trusty/man8/update-alternatives.8.html . And/or set the PATH variable appropriately.

A complete build log could help to debug what is going on.

**Comment by jfeng08** [comment]
Ian,
Here is the log file from our host:
[20191220091556.txt](https://github.com/CoolProp/CoolProp/files/4016364/20191220091556.txt)

Thanks!

**Comment by ibell** [comment]
Did you notice this error: 

``#error These bindings need PHP5 - to generate PHP7 bindings use: swig -php7``?

**Comment by jfeng08** [comment]
Ian,
We successfully compiled CoolProp with php7.3.

Unfortunately we have to use the HEOS backend, and some input pairs generate errors, but they work well using the REFPROP backend with php5.4.

$CO2 = ConcreteState::factory("HEOS", "CO2");
$p = 6618479;
$T = 297.679692581;
$CO2->specify_phase(CoolProp::iphase_gas);
$CO2->update(PT_INPUTS, $p, $T);
$densityMass = $CO2->rhomass();
Fatal error: Uncaught exception 'Exception' with message 'solver_rho_Tp was unable to find a solution for T= 297.68, p=6.61848e+06, with guess value 13335.6 with error: The molar density of -16904.411443 mol/m3 is below the minimum of 0.000000 mol/m3' in...

With the REFPROP backend, the same code can give us "densityMass of CO2 is 290.045989109".

Is there any way that we still use REFPROP with php7.3? For example, put the _fluids_ and _mixtures_ folders from REFPROP into somewhere on the server?

Thanks,

**Comment by ibell** [comment]
In theory, yes, it should be possible to use REFPROP through CoolProp's PHP interface.  In practice, I'm not sure how to do it.  You'll need to investigate on your side, especially looking into how shared library loading and shared library resolution is handled.  You might need to add location of REFPROP folder to PATH variable (or PHP's internal version of this idea).  

What version of CoolProp do you use?  There aren't large pockets of failures for CO2 in the consistency plots: http://www.coolprop.org/fluid_properties/fluids/CarbonDioxide.html#consistency-plots

**Comment by jfeng08** [comment]
This is the version we use: CoolProp version: 6.3.1dev

**Comment by jfeng08** [comment]
Yesterday I followed the instructions here (https://github.com/jowr/librefprop.so), this morning I included /opt/refprop/ in the code, and the REFPROP backend works!!!

Ian, thanks for all your help!

**Comment by ibell** [comment]
Great news! 

FYI, the librefprop repo is deprecated, this is the more current recommendation: https://github.com/usnistgov/REFPROP-cmake

**Comment by jfeng08** [comment]
Replaced the deprecated librefprop with the new repo built with CMake. 

On step 6, I got the following:
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

Do they really matter?

**Comment by ibell** [comment]
Seems like you are using REFPROP 9 to get those warnings, but those are more warnings than errors, so it should still work.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
