### ISSUE TITLE
Incompressible docs not building properly

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1786]
Here is a snippet from the build log: 
```
worker_1  | ####################################
worker_1  | Running a nightly build on Sat Jan 12 11:02:47 UTC 2019
worker_1  | ####################################
worker_1  | /coolprop/dev/incompressible_liquids /coolprop/Web/scripts
worker_1  | Generating fitting reports
worker_1  | Traceback (most recent call last):
worker_1  |   File "all_incompressibles.py", line 2, in <module>
worker_1  |     from CPIncomp.WriterObjects import SolutionDataWriter
worker_1  |   File "/coolprop/dev/incompressible_liquids/CPIncomp/WriterObjects.py", line 23, in <module>
worker_1  |     import csv, codecs, cStringIO
worker_1  | ModuleNotFoundError: No module named 'cStringIO'
worker_1  | Creating example figures
worker_1  | ./fluid_properties.Incompressibles.sh: line 10: pdfnup: command not found
worker_1  | ./fluid_properties.Incompressibles.sh: line 11: convert: command not found
worker_1  | ./fluid_properties.Incompressibles.sh: line 12: convert: command not found
```

So far as I can tell, the things missing are pdfnup, imageMagick, and the WriterObjects.py neeeds to be updated to Python 3.x. The changes to docker specification need to happen here: https://github.com/CoolProp/CoolProp/blob/master/Web/docker/docworker.Dockerfile

See also #1784

**Comment by ibell** [comment]
``json.encoder.FLOAT_REPR`` seems to have been dropped in Python 3.x

**Comment by ibell** [comment]
in ``dev/incompressible_liquids/CPIncomp/WriterObjects.py``.  I fixed the cStringIO issue

**Comment by ibell** [comment]
I tried too to fix the json issues, but I could figure out how to make the necessary fixes and gave up.

**Comment by ibell** [comment]
Here is one idea, but I don't think it is quite right: https://stackoverflow.com/a/29066406
