### ISSUE TITLE
CoolProp inside docker build can't find REFPROP v10 mixtures 

### ISSUE THREAD

**Issue by dshen109** [CoolProp/CoolProp#1829]
### Description

[Corresponding REFPROP-cmake repo issue thread](https://github.com/usnistgov/REFPROP-cmake/issues/30)

I am installing REFPROP v10 and CoolProp inside a docker container. To build REFPROP, I'm using [Ian Bell's](https://github.com/usnistgov/REFPROP-cmake) cmake repo. The build executes successfully and I am able to use REFPROP through CoolProp in Python, but _only_ for pure fluids. I am able to use mixtures if I run commands from the `/opt/refprop` folder where I have copied the REFPROP files, but nowhere else. Setting the `ALTERNATIVE_REFPROP_PATH` using `CP.set_config_string(CP.ALTERNATIVE_REFPROP_LIBRARY_PATH, '/opt/refprop/')` does not solve my issue.

Contents of my local Dockerfile:
```FROM python:3.7 as build

# Install dependencies needed to build C extensions
RUN apt-get -y -m update && \
    apt-get install -y cmake g++ gfortran python-pip python3-dev

RUN pip install numpy six

WORKDIR /usr/local/refprop

# Copy in the refprop repo for building
COPY . .

# Make the default refprop location
RUN mkdir /opt/refprop

# Set path
ENV LD_LIBRARY_PATH="/opt/refprop:/usr/local/lib:$LD_LIBRARY_PATH"
ENV PATH="/opt/refprop:$PATH"
ENV RPPREFIX="/opt/refprop:/usr/local/lib:$RPPREFIX"

WORKDIR /usr/local/refprop/build

RUN cmake .. -DREFPROP_FORTRAN_PATH=/usr/local/refprop/files/fortran -DCMAKE_BUILD_TYPE=Release && \
    cmake --build .

# copy files to the default refprop locations
COPY files/fluids /opt/refprop/fluids/
COPY files/mixtures /opt/refprop/mixtures/
RUN cp -r /usr/local/refprop/build/librefprop.so /opt/refprop/librefprop.so
RUN cp -r /usr/local/refprop/build/librefprop.so /usr/local/lib/librefprop.so

WORKDIR /usr/local/refprop/

# Used for testing, doesn't hurt anything except image size
RUN pip install coolprop
```

### Steps to Reproduce

1. Recursively clone the NIST REFPROP cmake repo: https://github.com/usnistgov/REFPROP-cmake
2. Copy above Dockerfile to repo root 
3. Make a `files` folder in repo root
4. Copy `FORTRAN`, `MIXTURES`, `FLUIDS` REFPROP folders into `files/` as lowercase directories (`FORTRAN` --> `fortran`)
5. run `docker build -t refprop .` from the repo root
6. Once build is completed, run `docker run -it refprop bash` to shell into the docker container
7. From /usr/local/refprop, open python
```
root@b050b185315f:/usr/local/refprop£ python
Python 3.7.2 (default, Dec 29 2018, 07:16:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import CoolProp.CoolProp as CP

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX : PropsSI("H","P",100000,"T",300,"REFPROP::R407A.MIX")

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
112653.67968889134

>>> CP.set_config_string(CP.ALTERNATIVE_REFPROP_LIBRARY_PATH, '/opt/refprop/')

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
Good news: It is possible to use REFPROP on your system! However, the library 
could not be loaded. Please make sure that REFPROP is available on your system.

Neither found in current location nor found in system PATH.
If you already obtained a copy of REFPROP from http://www.nist.gov/srd/, 
add location of REFPROP to the PATH environment variable or your library path.

In case you do not use Windows, have a look at https://github.com/jowr/librefprop.so 
to find instructions on how to compile your own version of the REFPROP library.

ALTERNATIVE_REFPROP_PATH: 
ERROR: Could not load REFPROP (/opt/refprop/) due to: /opt/refprop/: cannot read file data: Is a directory. Make sure the library is in your system search path. In case you run 64bit Windows and you have a REFPROP license, try installing the 64bit DLL from NIST. 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("H","P",100000,"T",300,"REFPROP::R407A.MIX")

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("H","P",100000,"T",300,"REFPROP::water")
```
8. Run Python from the refprop folder: `cd /opt/refprop && python` to see CoolProp work inside the REFPROP folder for both fluids and mixtures.
```
root@b050b185315f:/usr/local/refprop£ cd /opt/refprop/ && python
Python 3.7.2 (default, Dec 29 2018, 07:16:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import CoolProp.CoolProp as CP

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
112653.67968889134

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
428158.16100957023
```

**Expected behavior:** 

CoolProp should have access to both pure and mixture REFPROP backends, not just pure fluids.

**Actual behavior:** 
CoolProp only has access to mixture REFPROP backends when commands are run from the `/opt/refprop` folder where the `mixtures` REFPROP folder is.

### Versions

**CoolProp Version:** [CoolProp version you are using]  
**Operating System and Version:** [OS you are running CoolProp on]  
**Access Method:** [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by dshen109** [comment]
Looks like the inputs to the [`SETMIXdll` function](https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETMIXdll) are wrong? The documentation suggests that the variable lengths `hMixNme_length` and `hFmix_length` need to be set, yet they're hardcoded as 255 in the CoolProp backend

More printing that I did:

```
>>> CP.set_debug_level(100)
>>> CP.AbstractState("REFPROP", "water")
AbstractState::factory(REFPROP,[ water ])
AbstractState::factory backend_library size: 7
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:441: Successfully loaded REFPROP fluid: /opt/refprop/fluids/WATER
<CoolProp.CoolProp.AbstractState object at 0x7fcb34a8eb90>
>>> CP.AbstractState("REFPROP", "R407A.MIX")
AbstractState::factory(REFPROP,[ R407A.MIX ])
AbstractState::factory backend_library size: 7
/opt/refprop/mixtures/R407A.MIX

_components_joined_raw /opt/refprop/mixtures/R407A.MIX

mix /opt/refprop/mixtures/R407A.MIX
mix length 31

hmx_bnc /opt/refprop/fluids/HMX.BNC
hmx_bnc length 27

ierr 101
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Unable to load mixture: R407A.MIX
```

**Comment by ibell** [comment]
This is a REFPROP bug, not CoolProp, as it turns out.  REFPROP tries to load propane.fld, which on linux does not exist (because the file is PROPANE.FLD)

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

root = '/home/ian/refprop'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
RP.REFPROPdll('R410A.MIX','QT','FDIR(1)',0,0,0,0,300,[1.0])
```
the salient part being the error message
```
[SETUP warning -101] Error in opening fluid file for component 21, which may be required for the calculation of transport properties: filename = propane.fld
```
Full output:
```
REFPROPdlloutput(z=array('d', [0.697614699375863, 0.302385300624138, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), Output=array('d', [-9999950.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), hUnits='/home/ian/refprop/fluids/R32.FLD', iUCode=0, x=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=-9999990.0, ierr=4294967195, herr='[SETUP warning -101] Error in opening fluid file for component 21, which may be required for the calculation of transport properties: filename = propane.fld')
```

**Comment by ibell** [comment]
Actually, for me loading the mix works fine on native linux build:
``` python
import CoolProp.CoolProp as CP
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, '/home/ian/refprop')
for fld in 'WATER','R410A','R410A.PPF','R410A.MIX':
    AS = CP.AbstractState('REFPROP', fld)
    print(fld, AS.rhomolar_critical())
```
yields
```
WATER 17873.7279956
R410A 6324.0
R410A.PPF 6324.0
R410A.MIX 5978.41690142842
```

**Comment by ibell** [comment]
Make sure you use case sensitive fluid file names

**Comment by ibell** [comment]
Indeed, with CoolProp, the fluids and mixtures folders need to be lower-case, if you put them in upper case, and provide the path via set_config_string, this dies here: https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L90

**Comment by ibell** [comment]
Aha, I see the problem in your code.  You need to provide just the ALTERNATIVE_REFPROP_PATH, as I did in my code, rather than the ALTERNATIVE_REFPROP_LIBRARY_PATH as you did in yours.

**Comment by dshen109** [comment]
Even with setting the `ALTERNATIVE_REFPROP_PATH` I'm unable to load all the REFPROP mixtures (R410A loads but not R410.MIX)

```python
>>> import CoolProp.CoolProp as CP
>>> CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, '/opt/refprop')
>>> for fld in 'WATER','R410A','R410A.PPF','R410A.MIX':
...     AS = CP.AbstractState('REFPROP', fld)
...     print(fld, AS.rhomolar_critical())
... 
WATER 17873.7279956
R410A 6324.0
R410A.PPF 6324.0
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "CoolProp/AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Unable to load mixture: R410A.MIX
```

Interestingly enough, I'm also able to load a subset of the mixtures without first setting the `ALTERNATIVE_REFPROP_PATH` -- for example, `R407A` is a problem child.

```python
>>> import CoolProp as CP
>>> AS = CP.AbstractState('REFPROP', "R410A")
>>> AS = CP.AbstractState('REFPROP', "R404A")
>>> AS = CP.AbstractState('REFPROP', "R407A")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Could not load these fluids: R407A
```

Here's the contents of my `refprop/mixtures` folder as a sanity check:

```
root@1deefdb0925c:/opt/refprop/mixtures# ls
AIR.MIX       R401A.MIX  R404A.MIX  R407E.MIX  R410A.MIX  R414B.MIX  R418A.MIX	R422B.MIX  R426A.MIX  R433A.MIX  R437A.MIX  R444A.MIX  R449A.MIX  R452B.MIX  R456A.MIX	R500.MIX   R508B.MIX  R515A.MIX
AMARILLO.MIX  R401B.MIX  R405A.MIX  R407F.MIX  R410B.MIX  R415A.MIX  R419A.MIX	R422C.MIX  R427A.MIX  R433B.MIX  R438A.MIX  R444B.MIX  R449B.MIX  R452C.MIX  R457A.MIX	R501.MIX   R509A.MIX  README.TXT
EKOFISK.MIX   R401C.MIX  R406A.MIX  R407G.MIX  R411A.MIX  R415B.MIX  R419B.MIX	R422D.MIX  R428A.MIX  R433C.MIX  R439A.MIX  R445A.MIX  R449C.MIX  R453A.MIX  R458A.MIX	R502.MIX   R510A.MIX
GLFCOAST.MIX  R402A.MIX  R407A.MIX  R407H.MIX  R411B.MIX  R416A.MIX  R420A.MIX	R422E.MIX  R429A.MIX  R434A.MIX  R440A.MIX  R446A.MIX  R450A.MIX  R454A.MIX  R459A.MIX	R503.MIX   R511A.MIX
HIGHCO2.MIX   R402B.MIX  R407B.MIX  R408A.MIX  R412A.MIX  R417A.MIX  R421A.MIX	R423A.MIX  R430A.MIX  R435A.MIX  R441A.MIX  R447A.MIX  R451A.MIX  R454B.MIX  R459B.MIX	R504.MIX   R512A.MIX
HIGHN2.MIX    R403A.MIX  R407C.MIX  R409A.MIX  R413A.MIX  R417B.MIX  R421B.MIX	R424A.MIX  R431A.MIX  R436A.MIX  R442A.MIX  R447B.MIX  R451B.MIX  R454C.MIX  R460A.MIX	R507A.MIX  R513A.MIX
NGSAMPLE.MIX  R403B.MIX  R407D.MIX  R409B.MIX  R414A.MIX  R417C.MIX  R422A.MIX	R425A.MIX  R432A.MIX  R436B.MIX  R443A.MIX  R448A.MIX  R452A.MIX  R455A.MIX  R460B.MIX	R508A.MIX  R513B.MIX
root@1deefdb0925c:/opt/refprop/mixtures# cat R404A.MIX 
R404A    [R-125/143a/134a (44/52/4)]
 97.60379855076445 345.27019337127246 3734.8865915479587 4.986471372004241
 3
R125.FLD
R134A.FLD
R143A.FLD
 .357816784026318
 3.82639950410712E-02
 .603919220932611
 0
root@1deefdb0925c:/opt/refprop/mixtures# cat R407A.MIX 
R407A    [R-32/125/134a (20/40/40)]
 90.1107325163305 355.39763942094527 4513.9506999229825 5.521838372025782
 3
R32.FLD
R125.FLD
R134A.FLD
 .346419854360797
 .300315552114308
 .353264593524896
 0
```

**Comment by ibell** [comment]
``` python
>>> AS = CP.AbstractState('REFPROP', "R410A")
>>> AS = CP.AbstractState('REFPROP', "R404A")
>>> AS = CP.AbstractState('REFPROP', "R407A")
```
are loading pseudo-pure EOS, not the mixture model: http://www.coolprop.org/fluid_properties/fluids/R410A.html#equation-of-state .  Your code should work, but obviously it doesn't.  Are you 100% sure that you are using REFPROP 10?

**Comment by ibell** [comment]
I can reproduce this now on linux, so we should be able to get to the bottom of it.  I see this behavior when I have copied fluids to FLUIDS and mixtures to MIXTURES

**Comment by ibell** [comment]
It's a REFPROP bug.  REFPROP does not load the fluid files correctly when an absolute path to the mixture file is provided.   In this case, you'll need to specify the mole fractions directly, that should still "work", but that's not a nice workaround.

```
/home/ian/Code/coolprop/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:378 Unable to load predefined mixture [/home/ian/refprop/mixtures/R410A.MIX] with ierr: [101] and herr: [[SETUP error 101] Error in opening file for component 1: filename = R32.FLD ```

**Comment by dshen109** [comment]
> ```python
> >>> AS = CP.AbstractState('REFPROP', "R410A")
> >>> AS = CP.AbstractState('REFPROP', "R404A")
> >>> AS = CP.AbstractState('REFPROP', "R407A")
> ```
> 
> are loading pseudo-pure EOS, not the mixture model: http://www.coolprop.org/fluid_properties/fluids/R410A.html#equation-of-state . Your code should work, but obviously it doesn't. Are you 100% sure that you are using REFPROP 10?

So even when I specify `REFPROP` as the backend in the AbstractState, it will default to the CoolProp routines?

I am 1000% sure I'm using REFPROP 10:
```
>>> CP.get_global_param_string("REFPROP_version")
'10.0'
```

**Comment by ibell** [comment]
No - when you specify "R410A", that is an alias to "R410A.PPF", not "R410A.MIX"; note the values that are returned in my code above.  In my opinion, this is a bug in REFPROP, but this is for historical reasons, and unlikely to change.  In either case, if 'REFPROP' is specified as backend, it still uses REFPROP to do the calculations.

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('/home/ian/refprop')
print(RP.SETMIXdll('/home/ian/refprop/mixtures/R410A.MIX','HMX.BNC','DEF'))
```

**Comment by ibell** [comment]
Gave me the error:
```
SETMIXdlloutput(ncc=2, hFiles='R32.FLD|R125.FLD|', z=array('d', [0.697614699375863, 0.302385300624138, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), ierr=101, herr='[SETUP error 101] Error in opening file for component 1: filename = R32.FLD')

**Comment by ibell** [comment]
And if I remove the mixtures folder:
```
ian@ian-ThinkPad-X220:~/refprop$ ls
fluids  FLUIDS  librefprop.so  MIXTURES
```
I get an encoding error from 
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('/home/ian/refprop')
print(RP.SETMIXdll('/home/ian/refprop/mixtures/R410A.MIX','HMX.BNC','DEF'))
```
of 
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-12-d1c5cb82d957> in <module>
      1 from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
      2 RP = REFPROPFunctionLibrary('/home/ian/refprop')
----> 3 print(RP.SETMIXdll('/home/ian/refprop/mixtures/R410A.MIX','HMX.BNC','DEF'))

~/miniconda3/envs/py/lib/python3.7/site-packages/ctREFPROP/ctREFPROP.py in SETMIXdll(self, hMixNme, hFmix, hrf)
   2882         self._SETMIXdll(hMixNme,hFmix,hrf,ct.byref(ncc),hFiles,z,ct.byref(ierr),herr,255,255,3,10000,255)
   2883 
-> 2884         return self._SETMIXdlloutput_tuple(ncc.value,trim(hFiles.raw),to_double_array(z),ierr.value,trim(herr.raw))
   2885 
   2886     def SETMODdll(self,ncomp,htype,hmix,hcomp):

~/miniconda3/envs/py/lib/python3.7/site-packages/ctREFPROP/ctREFPROP.py in trim(s)
     37 
     38 def trim(s):
---> 39     return s.replace(b'\x00',b'').strip().decode('utf-8')
     40 
     41 def get_default_DLL_extension():

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1: invalid start byte


```

**Comment by ibell** [comment]
Basically, I think it is not possible to get this to work reliably without calling SETPATHdll.  When you do call SETPATHdll, it works, but it appears that there are still initialized variables in SETMIXdll:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('/home/ian/refprop')
RP.SETPATHdll('/home/ian/refprop')
print(RP.SETMIXdll('/home/ian/refprop/mixtures/R410A.MIX','HMX.BNC','DEF'))
```
yielding
```
SETMIXdlloutput(ncc=2, hFiles='R32.FLD|R125.FLD|', z=array('d', [0.697614699375863, 0.302385300624138, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), ierr=4294967195, herr='[SETUP warning -101] Error in opening fluid file for component 21, which may be required for the calculation of transport properties: filename = propane.fld')
```

**Comment by dshen109** [comment]
I was able to get it to work by doing the `SETPATHdll` call. Thanks for the help!

```python
>>> from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
>>> RP = REFPROPFunctionLibrary('/opt/refprop')
>>> RP.SETPATHdll('/opt/refprop')
>>> import CoolProp.CoolProp as CP
>>> CP.AbstractState("REFPROP", "R407A.MIX")
<CoolProp.CoolProp.AbstractState object at 0x7ff77d981110>
>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
428158.16100957023
```

Will there be a patch soon for  CoolProp to automatically call SETPATHdll based on the default path, or would it be better for me to make a local `CoolProp` wrapper library that automatically calls `ctREFPROP` to set the path?

**Comment by ibell** [comment]
A warning...  you are now entering the danger zone.  On most platforms, the
same library can only be loaded once into a process, and calls to this
library all call the same chunk of memory, the source of some very
surprising behaviors.  While your solution should work, a better solution
is to wait for REFPROP to fix this bug.  In the meantime, your solution
should work.  I don't remember why we went away in CoolProp from also
calling SETPATHdll when a different path was specified, but I think it was
to work around a different path-related bug.

**Comment by dshen109** [comment]
ok, good to know!

**Comment by kaern** [comment]
I have the exact same issue as this and could resolve it calling the RP.SETPATHdll('/opt/refprop'). It did work with REFPROP 9.1 but not with REFPROP 10 .. 

![Image](https://github.com/user-attachments/assets/c3a721e1-2f7f-400a-b801-dc269c1eb504)

**Comment by ibell** [comment]
I have great news for all of you... I too was getting frustrated by the annoyance of working with REFPROP in CoolProp. I fixed that by enabling the ability to set the ``COOLPROP_REFPROP_ROOT`` environment variable: https://coolprop.github.io/CoolProp/coolprop/REFPROP.html#path-issues . You'll need to build from source, or wait a short while (a few days) while I prepare the 6.8.0 release.
