### ISSUE TITLE
REFPROP tabular interpolation gives inputs not in range ValueError

### ISSUE THREAD

**Issue by dshen109** [CoolProp/CoolProp#1830]
### Description

Using the tabular interpolation with REFPROP mixtures doesn't work when `AbstractState.update` is called. Also, the REFPROP tables take quite a long time to generate and the logs don't seem to show the tables being generated correctly.

### Steps to Reproduce

```
import CoolProp.CoolProp as CP
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

# Needed because REFPROPv10 needs to have its path set.
REFPROP_PATH = '/opt/refprop'
RP = REFPROPFunctionLibrary(REFPROP_PATH)
RP.SETPATHdll(REFPROP_PATH)

CP.set_debug_level(10)

state = CP.AbstractState(
    "BICUBIC&REFPROP", "R407A.MIX")
state.update(CP.PT_INPUTS, 4e5, 300)
state.rhomass()
```

**Expected behavior:** 
`AbstractState.update` works.

**Actual behavior:** [What actually happens]

```
x: -nan y: -nan
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
 rhomolar is invalid
x: -nan y: -nan
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
 rhomolar is invalid
x: -nan y: -nan
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:286: The current fluid can be reused; /opt/refprop/mixtures/R407A.MIX and /opt/refprop/mixtures/R407A.MIX match 
 rhomolar is invalid
Tables loaded
Calculated bicubic coefficients for 0 good cells in 0.002323 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.004038 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.00564 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.00757 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.003569 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.006556 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.008489 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.010203 sec.
Remapped 0 cells
>>> a.update(CP.PT_INPUTS, 4e5, 300)
update(PT_INPUTS,400000,300)
inputs are not in rangeTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp/AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update
ValueError: inputs are not in range, p=100000 Pa, T=300 K
```

### Versions

**CoolProp Version:** v6.3.0
**Operating System and Version:** Debian 9 docker container  
**Access Method:** Python 3.7

**Comment by ibell** [comment]
What happens if you do the same thing, but use the HEOS backend instead of
REFPROP?  It's the same model.  Seems like some part of the calculations
with REFPROP failed, maybe there is a bug in the calculation of the
saturation spline.  What are the sizes of the generated tables?

**Comment by dshen109** [comment]
The HEOS backend also gives a bunch of error logs (although the table generation is a _lot_ faster, 10s compared to 10m with the REFPROP backend).
```
>>> state = CP.AbstractState("BICUBIC&HEOS", "R407A.MIX")

...
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=117; ipsat_max=120
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
Tables loaded
Calculated bicubic coefficients for 0 good cells in 0.001715 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.002736 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.00368 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.004622 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.001641 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.003329 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.00549 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.007554 sec.
Remapped 0 cells
>>> state.update(CP.PT_INPUTS, 4e5, 300)
update(PT_INPUTS,400000,300)
inputs are not in rangeTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp/AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update
ValueError: inputs are not in range, p=400000 Pa, T=300 K
>>> state.rhomass()
0.55985343306987
```

**Comment by dshen109** [comment]
Here's the size of the tables.

```bash
root@97b3ddc7bc21:/usr/src/app/.coolprop/tables# ls -lh HelmholtzEOSBackend\(R32\[0.3464198544\]\&R125\[0.3003155521\]\&R134a\[0.3532645935\]\)/
total 120K
-rw-r--r-- 1 root root 34K May 29 00:33 phase_envelope.bin.z
-rw-r--r-- 1 root root 727 May 29 00:33 pure_saturation.bin.z
-rw-r--r-- 1 root root 39K May 29 00:33 single_phase_logpT.bin.z
-rw-r--r-- 1 root root 40K May 29 00:33 single_phase_logph.bin.z
```

**Comment by ibell** [comment]
What if you define the mixture, rather than using the predefined one?  Can
you use R410A.mix to test whether its a binary versus ternary mixture
problem?

Also, your files are tiny, they don't seem correct. It should be more like
20 MB in total.

**Comment by dshen109** [comment]
Using R410A.mix doesn't work either:

```
state = CP.AbstractState("BICUBIC&HEOS", "R410A.mix")
...
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=116; ipsat_max=116
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=116; ipsat_max=116
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=116; ipsat_max=116
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=116; ipsat_max=116
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=116; ipsat_max=116
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
Tables loaded
Calculated bicubic coefficients for 0 good cells in 0.001624 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.002576 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.003586 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.004435 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.001614 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.002485 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.003399 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.004275 sec.
Remapped 0 cells
>>> state.update(CP.PT_INPUTS, 4e5, 300)
update(PT_INPUTS,400000,300)
inputs are not in rangeTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp/AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update
ValueError: inputs are not in range, p=400000 Pa, T=300 K
```

**Comment by dshen109** [comment]
Using a predefined mixtures works.

```
>>> state = CP.AbstractState("BICUBIC&REFPROP", "Methane&Ethane")
>>> state.set_mole_fractions([0.2,0.8])
>>> state.update(CP.PQ_INPUTS, 101325, 1)
>>> state.rhomass()
1.8945280714991528
```

**Comment by ibell** [comment]
What about R410 but defining the composition directly?  Maybe there is
something wrong with predefined mixtures in general, but nobody has
reported this yet to my knowledge

**Comment by dshen109** [comment]
Defining the composition directly works (although the logs when constructing the table are quite strange):

```
state = CP.AbstractState("BICUBIC", "R32&R125")
state.set_mole_fractions([0.5,0.5])
...
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
x: -nan y: -nan
is_inside(-nan,-nan); iTsat_max=115; ipsat_max=115
 Input is out of range for primary value [-nan], inputs were (P,-nan,T,-nan); no intersections found
Tables loaded
Calculated bicubic coefficients for 0 good cells in 0.001602 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.00251 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.003457 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.004332 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.001665 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.002597 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.003687 sec.
Remapped 0 cells
Calculated bicubic coefficients for 0 good cells in 0.004595 sec.
Remapped 0 cells
>>> state.update(CP.PQ_INPUTS, 4e5, 1)
update(PQ_INPUTS,400000,1)
>>> state.rhomass()
18.636011492187503
```

**Comment by dshen109** [comment]
Seems to work when I specify REFPROP as well:

```
>>> import CoolProp.CoolProp as CP
>>> from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
>>> 
>>> REFPROP_PATH = '/opt/refprop'
>>> RP = REFPROPFunctionLibrary(REFPROP_PATH)
>>> RP.SETPATHdll(REFPROP_PATH)
>>> 
>>> CP.set_config_string(
...     CP.ALTERNATIVE_TABLES_DIRECTORY, "/usr/src/app/.coolprop/tables/")
>>> state = CP.AbstractState("BICUBIC&REFPROP", "R32&R125")
>>> state.set_mole_fractions([0.5,0.5])
>>> state.update(CP.PQ_INPUTS, 4e5, 1)
>>> state.rhomass()
18.248244046009525
```

**Comment by dshen109** [comment]
Found some more weirdness -- only PQ inputs work for updating the AbstractState when using the REFPROP mixtures with bicubic interpolation and HEOS.

```python
>>> state = CP.AbstractState("BICUBIC&HEOS", "R407A.MIX")
>>> state.update(CP.PQ_INPUTS, 4e5, 1)
>>> state.hmass()
394001.3471044169
>>> state.T()
267.3642578125


>>> state.update(CP.QT_INPUTS, 1, 267)
>>> state.hmass()
nan
>>> state.T()
nan

>>> state.update(CP.PT_INPUTS, 4e5, 267)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp/AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update
ValueError: inputs are not in range, p=400000 Pa, T=267 K
```
