### ISSUE TITLE
Python3, AbstractState & boolean stings -

### ISSUE THREAD

**Issue by Enesma** [CoolProp/CoolProp#1831]
### Description

All I wanted was a log p h Diagram... :-)
I chose the example from the webpage
```
import CoolProp
from CoolProp.Plots import PropertyPlot
plot = PropertyPlot('R290', 'ph')
plot.calc_isolines()
plot.show()
```
And hit an error: 

File "C:/Programfiles/Anaconda3/lib/site-packages/CoolProp/Plots/Common.py", line 38, in get_critical_point
new_state = AbstractState(state.backend_name(), '&'.join(state.fluid_names()))
TypeError: sequence item 0: expected str instance, bytes found

My collegue could do it on Anaconda 2, on Anaconda 3 he hit the same error.
After some debugging we found that the Python3 way to handle "Bytes literals" is different to Python2.
See [the b character](https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal)

I tried to figure out, what the correct line should be instead of 
Line 38: new_state = AbstractState(state.backend_name(), '&'.join(state.fluid_names()))

But it seems to me AbstractState is defined in the C code and I am not good enough to get there.
I hope, I satsified all infos for a bug report... A new line 38 would be great :-)

### Steps to Reproduce

Run the example under Python 3

**Expected behavior:** A beautiful log p h digram appers

**Actual behavior:** File "C:/Programfiles/Anaconda3/lib/site-packages/CoolProp/Plots/Common.py", line 38, in get_critical_point
new_state = AbstractState(state.backend_name(), '&'.join(state.fluid_names()))
TypeError: sequence item 0: expected str instance, bytes found

### Versions

**CoolProp Version:** CoolProp 6.2.1 (as supplied here https://anaconda.org/search?q=CoolProp) 
**Operating System and Version:** Win10, Anaconda3, Spyder 3.3.3, Python 3.6.8
**Access Method:** Spyder

**Comment by jha92** [comment]
Hello,
@Enesma and I investigated a bit more in this error. It is really only related to b-thing:
Python 2.7:
```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> test = [b't',b's']
>>> '&'.join(test)
't&s'
```
whereas with Python 3.6:
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> test = [b't',b's']
>>> '&'.join(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sequence item 0: expected str instance, bytes found
```
The fix is in this case a decoding step of the list with:
```
>>> test = [t.decode('UTF8') for t in test]
>>> test
['t', 's']
>>> '&'.join(test)
't&s'
```

So the same would work for line 38, by inserting this code
```
fluid_names = [x.decode('UTF8') for x in state.fluid_names()]
new_state = AbstractState(state.backend_name(), '&'.join(fluid_names))
```

Maybe, it is also possible to change something in the AbstractState class itself, so this here is only a quick hack, not sure about other influences.

**Comment by Enesma** [comment]
The code worked fine on my win machine after closing and opening Spyder again.
The 'UTF-8' propapbly caused some issues.
No understanding why.

**Comment by jowr** [comment]
Please note that the plotting is not very mature.

However, this looks like a more general issue. Could you prepare a simple example to reproduce the error reliably?

**Comment by Enesma** [comment]
After filing this issue I found the CoolPlot package and forced its installation.
The Common.py file has been overwritten and the line is completely gone.
I just found out while looking for a different example. Before it was working with the lines from @jha92.

So replication of the issue would be uninstalling CoolPlot and running the example mentioned at the beginning on Python 3.

Would love to help develope the CoolPlot package further. I am actually right now transcriping a Matlab code with refprop I had for a log ph diagram to Python and CoolProp.

**Comment by jowr** [comment]
Please note that I created CoolPlot a few days ago - you should use it at the moment it is a moving target.

**Comment by jowr** [comment]
You are more than welcome to help with CoolPlot - just let me know what you would like to do.

**Comment by Enesma** [comment]
I converted my mtlab code over that last two days. Still pretty new to Python...
I am only srtarting to understand the CoolPlot Code.
My main interest is ph diagrams, Tp diagrams and plotting on those in Python (before it was Matlab)
So anything in that direction... Some way to contact you / the team more privately to discuss?
