### ISSUE TITLE
TypeError in Python 3 module when importing built sdist

### ISSUE THREAD

**Issue by bryanwweber** [CoolProp/CoolProp#1832]
### Description

Building the 6.3.0 source distribution for Python results in an error on importing CoolProp in Python 3.

```python
>>> import CoolProp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bryan/GitHub/CoolProp/wrappers/Python/.venv/lib/python3.7/site-packages/CoolProp/__init__.py", line 22, in <module>
    __fluids__ = CoolProp.get_global_param_string('fluids_list').split(',')
  File "CoolProp.pyx", line 277, in CoolProp.CoolProp.get_global_param_string
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found
```

The same error occurs for at least Python 3.7.3 and 3.6.8. I've also confirmed the error on the most recent commit on `master`. I first noticed this on conda-forge/coolprop-feedstock#5 where the build failed (conda-forge requires building from the sdist), although unfortunately those build logs don't seem to be available. In any case, I was able to reproduce it locally on my macOS 10.14. This does not reproduce for Python 2, that seems to work fine.

This problem does not occur with the wheel install. I'm not sure why this is only a problem *now*, why it hasn't come out before. 

### Steps to Reproduce

1. `pip install --no-binary :all: coolprop` (the `--no-binary :all:` forces the build/install from the sdist)
2. `import CoolProp`

or

1. `cd wrappers/Python/pypi`
2. `python prepare_pypi --dist-dir=/some/directory`
3. `cd /some/directory && tar -xzf CoolProp-6.3.1.dev0.tar.gz && cd CoolProp-6.3.1.dev0`
4. `python -m pip install --no-deps --ignore-installed .` (this is the conda-forge build command)

**Expected behavior:** CoolProp imports correctly

**Actual behavior:** An error appears

### Versions

**CoolProp Version:** 6.3.0/master
**Operating System and Version:** macOS 10.14
**Access Method:** Python

### Additional Information

There doesn't seem to be a whole lot on Google about this issue, or maybe my google-fu is failing. One possible resolution is to remove the `string` here

https://github.com/CoolProp/CoolProp/blob/fb1ff7de7de448a1f32cbabf2c8372d0719015b5/wrappers/Python/CoolProp/CoolProp.pyx#L277-L278

(and other similar places). I'm not sure how that would affect Python 2 compatibility though. 

One other thing I noticed about generating the sdist is that no Cython language level is specified which generates a warning. At the moment, the default is Python 2, so it should be the same as when the wheel is built, but that will change in the future. If you're interested, I'd be happy to go through and change everything in the Cython code to be `language_level=3` compatible.

**Comment by ibell** [comment]
I think this behavior is only being identified now because everybody uses the binary wheels, as I would 100% recommend as well, unless you are up for working through some hiccups.

While I'm a fairly experienced Python developer, I feel like a total newbie every time I have to do anything with strings.  And Cython adds a whole new set of string wrinkles into the mix.  Especially problematic here is that all strings in CoolProp c++ core are ASCII, and Python gives you the full spectrum of encoding options.

I would very much welcome a PR that fixes the Cython language level along with some tests for python 2.7 to make sure things haven't gotten borked too much.  But Python 2.7 is end-of-life in a few months, so I would _maybe_ even accept borking Python 2.7.

**Comment by bryanwweber** [comment]
Hi @ibell! Thanks for the quick response. The reason I'm surprised this hasn't shown up before is that conda-forge had at least version 6.2.1 (and possibly more) and those were all built with the sdist (per conda-forge policy).

To be clear, I'm not sure what the solution to this problem is; its possible that converting everything to `language_level=3` would fix the problem, but I'm doubtful that's the case. Fortunately, the `language_level` shouldn't have an impact on the supported versions of Python because the code is compiled down to a shared library; the `language_level` only affects how the Cython code is written.

I'll need to do some reading and experimenting, but I'll try to put a fix together for this issue. Of course, my understanding of the reason for the 2->3 transition was strings (among other things), so I don't think anyone really gets it :smiley: If everything in CoolProp is ASCII, encoding/decoding to/from UTF-8 shouldn't be a problem, and would be future compatible if any Unicode strings get added in the future (Refrigerant 😄 🎉 🌎  is just around the corner I hear 😂 ). Of course, that makes Python 2 support tricky. Do you have a plan to drop Python 2 at some point?

**Comment by emmaddeveloper** [comment]
Hi @bryanwweber 
Am new to python. Had similar issue. Please did you get a fix.

**Comment by emmaddeveloper** [comment]
Hi@ibell
Please I have similar issue. Any help?

**Comment by ibell** [comment]
I'm not sure what the problem is, since I have never experienced this issue
before.  If you're just getting started, first use the pip install route,
understand how that works, before getting into building yourself

**Comment by jawona** [comment]
Hi,
this is my first comment on Github and I´m almost new to programming, so please be soft on me.

I had the same problem (TypeError). Even if I just imported CoolProp without calling any function. I installed CoolProp using "sudo pip3 install CoolProp".

After some trouble I tried the manual installation following the docs (http://coolprop.org/coolprop/wrappers/Python/index.html#python). Now it works fine.

I just thought this might help other users.

**Comment by ibell** [comment]
Hi @jawona Can you please open a new issue with this problem and fill out the entire template?  If you had this problem, I doubt you are the only one, and I'd like to get to the bottom of this.  I haven't had any experience with this problem, so I don't know where to start to look into it.

I'm glad though that you found a solution, even if inconvenient.

**Comment by jawona** [comment]
Hi @ibell,
ok, I will open a new issue.
Btw: I think it is comfy to install something manually, WHEN there is an instruction ;-)
Thanks for that!

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
