### ISSUE TITLE
Coolprop can't acess refprop lib

### ISSUE THREAD

**Issue by SauloLrocha** [CoolProp/CoolProp#1844]
### Description

I need to access the Refprop database through the Coolprop to make a calculation using other fluids besides the ones in the Coolprop database.

I tried the command to change the refprop location folder but I have the same error message 

**-->Steps to Reproduce**
`from CoolProp.CoolProp import PropsSI`
`xpto = PropsSI("T","P",101325,"Q",1,"REFPROP::Water")`

**-->Error message**
ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("T","P",101325,"Q",1,"REFPROP::Water")

### Versions
Refprop Version: 9.1
CoolProp Version: Version: 6.3.0
Operating System and Version: Windows 10 Pro  
Access Method: Python

**Comment by ibell** [comment]
You need to specify the PATH for REFPROP 9.1: http://www.coolprop.org/coolprop/REFPROP.html#path-issues

Are you using 64-bit or 32-bit Python and OS?  If 64-bit, and you don't have the file REFPRP64 email me at my NIST email and I'll send you the update

**Comment by mibogi** [comment]
Hi to All,
i have smiliar issue:

for my code
package com.example.demo;
import com.example.demo.CoolProp;

public class RegrigerantData {
    static {
        System.load("/media/correctpath/LocalPartition/blah/Refrigeration/RefrigerationProperties/src/main/java/com/example/demo/libCoolProp.so");
	System.out.println("Library Loaded");
    }

    public static void main(String argv[]){
        System.out.println("**************** INFORMATION ***************");
        System.out.println("This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell");
      
        System.out.println("Critical temperature of R134a:" + " " + CoolProp.Props1SI("R134a", "Tcrit") + " " + "K");
     
           }
}

I receive following trace
Library Loaded
**************** INFORMATION ***************
This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'double com.example.demo.CoolPropJNI.Props1SI(java.lang.String, java.lang.String)'
	at com.example.demo.CoolPropJNI.Props1SI(Native Method)
	at com.example.demo.CoolProp.Props1SI(CoolProp.java:96)
	at com.example.demo.RegrigerantData.main(RegrigerantData.java:14)

Obviously it tells me that there is an issue in classes CoolPropJNI and CoolProp. I added to each of them classes the following peace of code:
  static {
        System.load("/media/correctpath/LocalPartition/blah/Refrigeration/RefrigerationProperties/src/main/java/com/example/demo/libCoolProp.so");
	System.out.println("Library Loaded");
    }


Library Loaded
**************** INFORMATION ***************
This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'double com.example.demo.CoolPropJNI.Props1SI(java.lang.String, java.lang.String)'
	at com.example.demo.CoolPropJNI.Props1SI(Native Method)
	at com.example.demo.CoolProp.Props1SI(CoolProp.java:102)
	at com.example.demo.RegrigerantData.main(RegrigerantData.java:14)

but still in vain...
Funny enough, it was yesterday that it worked. I am using Spring STS IDE, but in this case i compiled  the files as well with javac *java. but there it seams that the Lib is not loaded.

Any chance to help me out? there will be more of me for sure, as i am trying to test the wrappers on Concurrency in java environment
BR
MiBogi

**Comment by ibell** [comment]
Please make sure that your example works outside the IDE; the IDE can do all sort of "creative" things.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
