### ISSUE TITLE
How CoolProp calculate CaCl2 brine properties?

### ISSUE THREAD

**Issue by gas0189** [CoolProp/CoolProp#1854]
Can CoolPorp calculate Calcium Chloride Brine properties?
If can, please show me a example.
Thank you every much!!!

```
>>> PropsSI('D','T',300,'P',101325,'INCOMP::MEG-20%')
1021.7622891189155
>>> PropsSI('D','T',300,'P',101325,'INCOMP::LiBr-20%')
1158.6968948459378
>>> PropsSI('D','T',300,'P',101325,'INCOMP::CaCl2-20%')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:43220)
  File "CoolProp\CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:43002)
  File "CoolProp\CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:41189)
ValueError: Initialize failed for backend: "INCOMP", fluid: "CaCl2" fractions "[ 0.2000000000 ]"; error: key [CaCl2] was not found in string_to_index_map in JSONIncompressibleLibrary : PropsSI("D","T",300,"P",101325,"INCOMP::CaCl2-20%")

```

**Comment by ibell** [comment]
Try the VCA fluid name.  Please see
http://www.coolprop.org/fluid_properties/Incompressibles.html#fitting-reports

**Comment by gas0189** [comment]
Yes, I got it.  Thanks @ibell .

```
>>> PropsSI('D','T',273.15,'P',101325,'INCOMP::VCA-20%')
1186.6774301805608
```
