### ISSUE TITLE
R511A corrected

### ISSUE THREAD

**Issue by WolfgangH692** [CoolProp/CoolProp#1902]
Hi over there,

R511A is a blend of propane(R290) and R152A, not DME (as in CoolProp).

Mass fractions:  propane=0.95, R152A=0.05 

Please delete the corresponding lines of CoolProp in predefined_mixtures.json
and insert the following lines:

{
    "fluids": [
      "PROPANE", 
      "R152A"
    ], 
    "mole_fractions": [
      0.966055868721912,
      0.0339441312780884      
    ], 
    "name": "R511A"
  }, 

In addition due to lacking binary data (Error: "could not match the binary pair")
calculations with the mixtures
    R413A, R424A, R426A, R429A, R435A,
    R437A, R438A, R445A, R446A, R447A,
    R448A, R450A, R513B
do not take place.

**CoolProp Version:** [CoolProp version you are using] … latest 
**Operating System and Version:** [OS you are running CoolProp on] ... Windows 10 
**Access Method:** [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)] ...  Excel

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
Actually, I believe that both of CoolProp and REFPROP are correct.  If you read standard 34 of ASHRAE, it is clear that R-511A is a 95/5 mass mixture of R-290 and R-E170 (which is DME).

**Comment by ibell** [comment]
What reference did you take that information from?

**Comment by WolfgangH692** [comment]
Hi Ian,

Sources:

1) Refprop 9.1

2) https://www.coolingpost.com/world-news/new-ashrae-refrigerant-standards/

both clearly saying that R511A is a blend of R290 (propane) and R152A (1,1-difluorethane)

Try in Excel:
 CoolProp:
 =PropsSI("Dmass";"T";273.15;"P";101325;"HEOS::R511A.mix")
 Refprop:
 =Density("R511A.mix";"TP";"SI";273.15;1.01325/10)
The results deviate by more than 1 %.

Wolfgang

**Comment by ibell** [comment]
I think then that REFPROP 9.1 and that web post are likely wrong.  The
standard is the canonical answer.

**Comment by WolfgangH692** [comment]
I agree, and try to fix it.

What can be done with the lacking binaries?

**Comment by WolfgangH692** [comment]
Ok, fixed it in Refprop 9.1, by creating a new mixture.
Now Refprop result and CoolProp result on R511A coincide.

Thanks for your help.

**Comment by WolfgangH692** [comment]
Hi Ian,

I would like to add that using REFPROP 9.1 to create a new mixture for R511A
REFPROP gave the warning (as soon as you try to store it under the old name R511A.mix):

"You are about to change an ASHRAE standard designation, do you wish to continue?"

Storing it nevertheless and returning to Excel the results from CoolProp and REFPROP 9.1
for R511A coincided.


Wolfgang

R511A with R152a is not seldom, see Federal Environment Office (UBA), Germany

https://www.umweltbundesamt.de/sites/default/files/medien/2503/dokumente/treibhauspotentiale_ausgewaehlter_verbindungen_und_deren_gemische.pdf

**Comment by WolfgangH692** [comment]
Using python to set binary pair data with:

import CoolProp.CoolProp as CP
CP.set_config_bool(CP.OVERWRITE_BINARY_INTERACTION, True)
CAS_R152a = CP.get_fluid_param_string('R152a','CAS')
CAS_R22 = CP.get_fluid_param_string('R22','CAS')
CP.apply_simple_mixing_rule(CAS_R152a,CAS_R22,'linear')
CP.set_mixture_binary_pair_data(CAS_R152a,CAS_R22,'zeta',1.0)

results in:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 265, in CoolProp.CoolProp.set_mixture_binary_pair_data
  File "CoolProp\CoolProp.pyx", line 269, in CoolProp.CoolProp.set_mixture_binary_pair_data
RuntimeError: Could not set the parameter [zeta] for the binary pair [75-37-6,75-45-6] - for now this is an error

The same happened for trying to set the parameter [xi].
What's wrong?

**Comment by ibell** [comment]
The answer is one you won't like: CoolProp does not support these parameters.  But the good news is that it is possible to convert them to the values gammaT and gammaV that CoolProp uses: http://www.coolprop.org/fluid_properties/Mixtures.html#appendix .  betaT and betaV should be 1.0.

**Comment by ibell** [comment]
Note also that I edited the formatting of your post

**Comment by WolfgangH692** [comment]
Ok, Ian, no problem. Thanks!

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
