### ISSUE TITLE
n-D inputs for list are broken

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1941]
@jowr ran into an issue with #1932 when building docs.  Basically, list inputs to PropsSI are now broken :/  I guess they need to be special cased, or the fix needs to be special cased.

```
Executing logo_2014.py
Traceback (most recent call last):
  File "logo_2014.py", line 64, in <module>
    p_sat = CP.CoolProp.PropsSI('P', 'T', T_sat, 'Q', [0] * len(T_sat), 'Water')
  File "CoolProp/CoolProp.pyx", line 373, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 414, in CoolProp.CoolProp.PropsSI
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by ibell** [comment]
Another special case, when multiple outputs are provided.  I think 5 keys are provided here.
``` python
Traceback (most recent call last):
  File "D4.py", line 46, in <module>
    RPdata = CP.PropsSI(normalkeys, 'T', T, 'Dmolar', rho, RPfluid)
  File "CoolProp/CoolProp.pyx", line 373, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 462, in CoolProp.CoolProp.PropsSI
ValueError: cannot reshape array of size 250 into shape (50,)
```

**Comment by jowr** [comment]
Hi - what would be the desired output here? It looks like my changes were not as well prepared as I thought.

**Comment by ibell** [comment]
I think in this case the returned matrix should be 5 columns by 50 rows.

There are a lot of special cases to worry about that I didn't think about before....

**Comment by jowr** [comment]
I was thinking something along these lines: 

1. Single output and only floats as input -> float
2. Single output and one nD array and one float as input -> nD array shaped like the input array
3. Single output and two nD arrays as input -> nD array shaped like the input arrays, error if shapes do not match
4. List of outputs and only floats as input -> list of floats (list is indexed like the list of outputs)
5. List of outputs and one nD array and one float as input -> list of nD arrays (list is indexed like the list of outputs, array is shaped like the input array)
6. List of outputs and two nD arrays as input -> list of nD arrays (list is indexed like the list of outputs, array is shaped like the input array, error if shapes do not match)

Would that work for you?

**Comment by jowr** [comment]
I assume that my last description is what we want - I'll go ahead and start implementing the changes.

**Comment by ibell** [comment]
Yes, I think that would be good, I guess we'll see after we start running some tests.  I'd like to get 6.4.1 out as soon as we can to get rid of this issue with 6.4.0 not loading properly.

**Comment by jowr** [comment]
Hm, I just revisited the C++ code and we actually do the opposite of what I suggested. I guess it makes sense to maintain the output structure for backwards compatibility. 

Maybe we should introduce some flag to control the output shape. Computing-wise it makes good sense to reuse the state object after the update call to get all outputs, but for the user it would make most sense to provide a list of numpy arrays, for example for plotting. Then one could just call the function with [Hmass,P] inputs and the output could be passed to either a scatter plot or even imshow without further modifications.

**Comment by ibell** [comment]
What do you think if I revert the changes to the N-D handling in the short
term, release 6.4.1 to fix the wheels, then we take the time to do it right
and think about all the corner cases?

**Comment by jowr** [comment]
Yes, let us do that. I did not expect so much trouble here - sorry for the mess. It is a good idea to rethink this a bit more.

**Comment by jowr** [comment]
I restore the branch that was closed when merging https://github.com/CoolProp/CoolProp/pull/1932. Let us continue the work on this topic in https://github.com/CoolProp/CoolProp/pull/1959

**Comment by ibell** [comment]
I think the `fast_evaluate` method on AbstractState is the "right" solution for getting many inputs at once as it forces the user to pre-build the buffer, and avoids copies across the interface. Closing this issue
