### ISSUE TITLE
CoolProp with version 6.3.0, use share library libCoolProp.so.6.3.0 in linux not work.

### ISSUE THREAD

**Issue by zhui19871** [CoolProp/CoolProp#1958]
1 In linux environment, use libCoolProp.so.6.3.0 with the java wrapper, but when use java Example throw follows problems:
 **************** INFORMATION ***************
This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
Exception in thread "main" java.lang.UnsatisfiedLinkError: CoolPropJNI.get_global_param_string(Ljava/lang/String;)Ljava/lang/String;
	at CoolPropJNI.get_global_param_string(Native Method)
	at CoolProp.get_global_param_string(CoolProp.java:128)
	at Example.main(Example.java:11)

and the Example.java code as follows:
     static {
        System.load("/usr/local/lib/libCoolProp.so");
    }

please support!

**Comment by ibell** [comment]
Did you put the shared library at the location in the error traceback?

**Comment by zhui19871** [comment]
Does it have anything to do with location? I understand it has nothing to do with location, and load the library had not throw error!

**Comment by ibell** [comment]
Did the library load properly? Are you sure? If so, I would be surprised if
the call to the global method fails.

**Comment by zhui19871** [comment]
Yes, I am sure, Because the code as follows: 
static {
System.load("/usr/local/lib/libCoolProp.so");
}
if not load properly, then throw error, but run this code is not throw error, so i think is load properly, and i am also surprised. and   
also not know where is wrong.


Today, I had build the libCoolProp.so.6.4.1 by follows document:
http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#shared-library, and run the Example.java, also throw error as above. 

so please help!

**Comment by ibell** [comment]
Can you please show the entire build process along with the shell output?
That might be instructive.

**Comment by zhui19871** [comment]
Ok, The build share library steps as follows :
1 Git clone code from gitHub:git clone https://github.com/CoolProp/CoolProp --recursive
2 cd CoolProp
3 mkdir build && cd build
4 /app/soft/cmake-3.18.0-Linux-x86_64/bin/cmake .. -DCOOLPROP_SHARED_LIBRARY=ON -DCMAKE_BUILD_TYPE=Release
-- COOLPROP_INSTALL_PREFIX=/app/soft/CoolProp/install_root
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 6.4.1
CMake Warning (dev) at CMakeLists.txt:252 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:253 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7")
CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (LibDL) does
  not match the name of the calling package (dl).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  dev/cmake/Modules/Finddl.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:289 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LibDL: /usr/lib64/libdl.so
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Setting bitness flag -m64
-- Library compilation detected:
-- Creating CoolProp, a 64-bit library
-- CMAKE_SYSTEM_NAME: Linux
-- COOLPROP_STATIC_LIBRARY: OFF
-- COOLPROP_SHARED_LIBRARY: ON
-- COOLPROP_OBJECT_LIBRARY: OFF
-- CONVENTION:
-- COOLPROP_LIBRARY_HEADER: include/CoolPropLib.h
-- COOLPROP_LIBRARY_SOURCE: src/CoolPropLib.cpp
-- COMPILE_FLAGS:  -DCOOLPROP_LIB -m64
-- LINK_FLAGS:  -m64
-- Configuring done
-- Generating done
-- Build files have been written to: /app/soft/CoolProp/build
5 /app/soft/cmake-3.18.0-Linux-x86_64/bin/cmake --build .
Scanning dependencies of target generate_headers
cpversion.h is up to date
version written to hidden file: /app/soft/CoolProp/.version for use in builders that don't use git repo
git version 1.8.3.1
git is accessible at the command line
git revision is e2b8d104b7bba71fc4dd77602c689ae0b502679f
gitrevision.h is up to date
all_fluids_JSON.h is up to date
all_incompressibles_JSON.h is up to date
mixture_departure_functions_JSON.h is up to date
mixture_binary_pairs_JSON.h is up to date
predefined_mixtures_JSON.h is up to date
all_cubics_JSON.h is up to date
cubic_fluids_schema_JSON.h is up to date
pcsaft_fluids_schema_JSON.h is up to date
all_pcsaft_JSON.h is up to date
mixture_binary_pairs_pcsaft_JSON.h is up to date
[  0%] Built target generate_headers
Scanning dependencies of target CoolProp
[  2%] Building CXX object CMakeFiles/CoolProp.dir/src/AbstractState.cpp.o
[  4%] Building CXX object CMakeFiles/CoolProp.dir/src/CPfilepaths.cpp.o
[  6%] Building CXX object CMakeFiles/CoolProp.dir/src/CPnumerics.cpp.o
[  8%] Building CXX object CMakeFiles/CoolProp.dir/src/CPstrings.cpp.o
[ 10%] Building CXX object CMakeFiles/CoolProp.dir/src/Configuration.cpp.o
[ 12%] Building CXX object CMakeFiles/CoolProp.dir/src/CoolProp.cpp.o
[ 14%] Building CXX object CMakeFiles/CoolProp.dir/src/CoolPropTools.cpp.o
[ 17%] Building CXX object CMakeFiles/CoolProp.dir/src/DataStructures.cpp.o
[ 19%] Building CXX object CMakeFiles/CoolProp.dir/src/Helmholtz.cpp.o
[ 21%] Building CXX object CMakeFiles/CoolProp.dir/src/HumidAirProp.cpp.o
[ 23%] Building CXX object CMakeFiles/CoolProp.dir/src/Ice.cpp.o
[ 25%] Building CXX object CMakeFiles/CoolProp.dir/src/MatrixMath.cpp.o
[ 27%] Building CXX object CMakeFiles/CoolProp.dir/src/ODEIntegrators.cpp.o
[ 29%] Building CXX object CMakeFiles/CoolProp.dir/src/PolyMath.cpp.o
[ 31%] Building CXX object CMakeFiles/CoolProp.dir/src/Solvers.cpp.o
[ 34%] Building CXX object CMakeFiles/CoolProp.dir/src/SpeedTest.cpp.o
[ 36%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/CubicBackend.cpp.o
[ 38%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/CubicsLibrary.cpp.o
[ 40%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/GeneralizedCubic.cpp.o
[ 42%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/UNIFAC.cpp.o
[ 44%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/UNIFACLibrary.cpp.o
[ 46%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/VTPRBackend.cpp.o
[ 48%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/IF97/IF97Backend.cpp.o
[ 51%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/FlashRoutines.cpp.o
[ 53%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/Fluids/Ancillaries.cpp.o
[ 55%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/Fluids/FluidLibrary.cpp.o
[ 57%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/HelmholtzEOSBackend.cpp.o
[ 59%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp.o
[ 61%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/MixtureDerivatives.cpp.o
[ 63%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/MixtureParameters.cpp.o
[ 65%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/PhaseEnvelopeRoutines.cpp.o
[ 68%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/ReducingFunctions.cpp.o
[ 70%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/TransportRoutines.cpp.o
[ 72%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/VLERoutines.cpp.o
[ 74%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/REFPROP/REFPROPBackend.cpp.o
[ 76%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/REFPROP/REFPROPMixtureBackend.cpp.o
[ 78%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleBackend.cpp.o
[ 80%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleFluid.cpp.o
[ 82%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleLibrary.cpp.o
[ 85%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Tabular/BicubicBackend.cpp.o
[ 87%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Tabular/TTSEBackend.cpp.o
[ 89%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Tabular/TabularBackends.cpp.o
[ 91%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/PCSAFT/PCSAFTBackend.cpp.o
[ 93%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/PCSAFT/PCSAFTFluid.cpp.o
[ 95%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/PCSAFT/PCSAFTLibrary.cpp.o
[ 97%] Building CXX object CMakeFiles/CoolProp.dir/src/CoolPropLib.cpp.o
[100%] Linking CXX shared library libCoolProp.so
[100%] Built target CoolProp
6 ll
total 5460
-rw-rw-r-- 1 appuser appuser   19699 Jul 28 09:07 CMakeCache.txt
drwxrwxr-x 6 appuser appuser    4096 Jul 28 09:11 CMakeFiles
-rw-rw-r-- 1 appuser appuser    3917 Jul 28 09:07 cmake_install.cmake
lrwxrwxrwx 1 appuser appuser      16 Jul 28 09:11 libCoolProp.so -> libCoolProp.so.6
lrwxrwxrwx 1 appuser appuser      20 Jul 28 09:11 libCoolProp.so.6 -> libCoolProp.so.6.4.1
-rwxrwxr-x 1 appuser appuser 5493544 Jul 28 09:11 libCoolProp.so.6.4.1
-rw-rw-r-- 1 appuser appuser   62155 Jul 28 09:07 Makefile
Then will see the share library had build.

and build the java Wrapper steps as follows:
First backup above share library use follow command: mv build/ build-bak, then execute follow command to generate java wrapper by follows document:http://www.coolprop.org/dev/coolprop/wrappers/Java/index.html#id2
1 mkdir build && cd build
2  /app/soft/cmake-3.18.0-Linux-x86_64/bin/cmake .. -DCOOLPROP_JAVA_MODULE=ON -DBUILD_TESTING=ON
-- COOLPROP_INSTALL_PREFIX=/app/soft/CoolProp/install_root
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 6.4.1
CMake Warning (dev) at CMakeLists.txt:252 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:253 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7")
CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (LibDL) does
  not match the name of the calling package (dl).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  dev/cmake/Modules/Finddl.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:289 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LibDL: /usr/lib64/libdl.so
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Found SWIG: /usr/bin/swig (found version "2.0.10")
-- Found Java: /app/jdk1.8.0_92/bin/java (found version "1.8.0_92")
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY)
-- JAVA_INCLUDE_PATH = /app/jdk1.8.0_92/include
CMake Deprecation Warning at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:592 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMakeLists.txt:1167 (SWIG_ADD_MODULE)


CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:633 (message):
  Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
  "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:593 (swig_add_library)
  CMakeLists.txt:1167 (SWIG_ADD_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:486 (message):
  Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
  flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:728 (SWIG_ADD_SOURCE_TO_MODULE)
  /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:593 (swig_add_library)
  CMakeLists.txt:1167 (SWIG_ADD_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /app/soft/CoolProp/build
3 /app/soft/cmake-3.18.0-Linux-x86_64/bin/cmake --build . --config Release
Scanning dependencies of target CoolProp_swig_compilation
[  2%] Swig compile /app/soft/CoolProp/src/CoolProp.i for java
/app/soft/CoolProp/include/Configuration.h:91: Warning 503: Can't wrap 'operator bool' unless renamed to a valid identifier.
/app/soft/CoolProp/include/Configuration.h:93: Warning 503: Can't wrap 'operator double' unless renamed to a valid identifier.
/app/soft/CoolProp/include/Configuration.h:95: Warning 503: Can't wrap 'operator std::string' unless renamed to a valid identifier.
/app/soft/CoolProp/include/Configuration.h:97: Warning 503: Can't wrap 'operator int' unless renamed to a valid identifier.
/app/soft/CoolProp/include/Configuration.h:117: Warning 516: Overloaded method CoolProp::ConfigurationItem::ConfigurationItem(configuration_keys,std::string const &) ignored,
/app/soft/CoolProp/include/Configuration.h:113: Warning 516: using CoolProp::ConfigurationItem::ConfigurationItem(configuration_keys,char const *) instead.
[  2%] Built target CoolProp_swig_compilation
Scanning dependencies of target generate_headers
cpversion.h is up to date
version written to hidden file: /app/soft/CoolProp/.version for use in builders that don't use git repo
git version 1.8.3.1
git is accessible at the command line
git revision is e2b8d104b7bba71fc4dd77602c689ae0b502679f
gitrevision.h is up to date
all_fluids_JSON.h is up to date
all_incompressibles_JSON.h is up to date
mixture_departure_functions_JSON.h is up to date
mixture_binary_pairs_JSON.h is up to date
predefined_mixtures_JSON.h is up to date
all_cubics_JSON.h is up to date
cubic_fluids_schema_JSON.h is up to date
pcsaft_fluids_schema_JSON.h is up to date
all_pcsaft_JSON.h is up to date
mixture_binary_pairs_pcsaft_JSON.h is up to date
[  2%] Built target generate_headers
Scanning dependencies of target CoolProp
[  4%] Building CXX object CMakeFiles/CoolProp.dir/CMakeFiles/CoolProp.dir/CoolPropJAVA_wrap.cxx.o
[  6%] Building CXX object CMakeFiles/CoolProp.dir/src/AbstractState.cpp.o
[  8%] Building CXX object CMakeFiles/CoolProp.dir/src/CPfilepaths.cpp.o
[ 10%] Building CXX object CMakeFiles/CoolProp.dir/src/CPnumerics.cpp.o
[ 12%] Building CXX object CMakeFiles/CoolProp.dir/src/CPstrings.cpp.o
[ 14%] Building CXX object CMakeFiles/CoolProp.dir/src/Configuration.cpp.o
[ 16%] Building CXX object CMakeFiles/CoolProp.dir/src/CoolProp.cpp.o
[ 18%] Building CXX object CMakeFiles/CoolProp.dir/src/CoolPropTools.cpp.o
[ 20%] Building CXX object CMakeFiles/CoolProp.dir/src/DataStructures.cpp.o
[ 22%] Building CXX object CMakeFiles/CoolProp.dir/src/Helmholtz.cpp.o
[ 25%] Building CXX object CMakeFiles/CoolProp.dir/src/HumidAirProp.cpp.o
[ 27%] Building CXX object CMakeFiles/CoolProp.dir/src/Ice.cpp.o
[ 29%] Building CXX object CMakeFiles/CoolProp.dir/src/MatrixMath.cpp.o
[ 31%] Building CXX object CMakeFiles/CoolProp.dir/src/ODEIntegrators.cpp.o
[ 33%] Building CXX object CMakeFiles/CoolProp.dir/src/PolyMath.cpp.o
[ 35%] Building CXX object CMakeFiles/CoolProp.dir/src/Solvers.cpp.o
[ 37%] Building CXX object CMakeFiles/CoolProp.dir/src/SpeedTest.cpp.o
[ 39%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/CubicBackend.cpp.o
[ 41%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/CubicsLibrary.cpp.o
[ 43%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/GeneralizedCubic.cpp.o
[ 45%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/UNIFAC.cpp.o
[ 47%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/UNIFACLibrary.cpp.o
[ 50%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Cubics/VTPRBackend.cpp.o
[ 52%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/IF97/IF97Backend.cpp.o
[ 54%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/FlashRoutines.cpp.o
[ 56%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/Fluids/Ancillaries.cpp.o
[ 58%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/Fluids/FluidLibrary.cpp.o
[ 60%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/HelmholtzEOSBackend.cpp.o
[ 62%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp.o
[ 64%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/MixtureDerivatives.cpp.o
[ 66%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/MixtureParameters.cpp.o
[ 68%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/PhaseEnvelopeRoutines.cpp.o
[ 70%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/ReducingFunctions.cpp.o
[ 72%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/TransportRoutines.cpp.o
[ 75%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Helmholtz/VLERoutines.cpp.o
[ 77%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/REFPROP/REFPROPBackend.cpp.o
[ 79%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/REFPROP/REFPROPMixtureBackend.cpp.o
[ 81%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleBackend.cpp.o
[ 83%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleFluid.cpp.o
[ 85%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Incompressible/IncompressibleLibrary.cpp.o
[ 87%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Tabular/BicubicBackend.cpp.o
[ 89%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Tabular/TTSEBackend.cpp.o
[ 91%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/Tabular/TabularBackends.cpp.o
[ 93%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/PCSAFT/PCSAFTBackend.cpp.o
[ 95%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/PCSAFT/PCSAFTFluid.cpp.o
[ 97%] Building CXX object CMakeFiles/CoolProp.dir/src/Backends/PCSAFT/PCSAFTLibrary.cpp.o
[100%] Linking CXX shared module libCoolProp.so
/bin/sh: 7z: command not found
gmake[2]: *** [libCoolProp.so] Error 127
gmake[2]: *** Deleting file `libCoolProp.so'
gmake[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
gmake: *** [all] Error 2
Then will see the java wrapper generated.

Now copy the Example.java to this directory, and change the load library as follows:
static {
System.load("/app/soft/CoolProp/build-bak/libCoolProp.so");
}
and execute as follows command:
javac *.java
java Example
now throw error as follows:
**************** INFORMATION ***************
This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
Exception in thread "main" java.lang.UnsatisfiedLinkError: CoolPropJNI.get_global_param_string(Ljava/lang/String;)Ljava/lang/String;
        at CoolPropJNI.get_global_param_string(Native Method)
        at CoolProp.get_global_param_string(CoolProp.java:136)
        at Example.main(Example.java:11)

so please help, which step is not right.

**Comment by jowr** [comment]
It looks like some Java stuff is missing - your logs contain the line `-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY)` and this might be related?

**Comment by zhui19871** [comment]
Today, I try again, and fixed this problem: Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY), but still not work.
The build log as follows:
/app/soft/cmake-3.18.0-Linux-x86_64/bin/cmake .. -DCOOLPROP_JAVA_MODULE=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
-- COOLPROP_INSTALL_PREFIX=/app/soft/CoolProp/install_root
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 6.4.1
CMake Warning (dev) at CMakeLists.txt:252 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:253 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7")
CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (LibDL) does
  not match the name of the calling package (dl).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  dev/cmake/Modules/Finddl.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:289 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LibDL: /usr/lib64/libdl.so
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Found SWIG: /usr/bin/swig (found version "2.0.10")
-- Found Java: /usr/local/java/jdk1.8.0_92/bin/java (found version "1.8.0_92")
-- Found JNI: /usr/local/java/jdk1.8.0_92/jre/lib/amd64/libjawt.so
-- JAVA_INCLUDE_PATH = /usr/local/java/jdk1.8.0_92/include
CMake Deprecation Warning at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:592 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMakeLists.txt:1167 (SWIG_ADD_MODULE)


CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:633 (message):
  Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
  "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:593 (swig_add_library)
  CMakeLists.txt:1167 (SWIG_ADD_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:486 (message):
  Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
  flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:728 (SWIG_ADD_SOURCE_TO_MODULE)
  /app/soft/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/UseSWIG.cmake:593 (swig_add_library)
  CMakeLists.txt:1167 (SWIG_ADD_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /app/soft/CoolProp/build

please help!

**Comment by ibell** [comment]
Try upgrading swig, your version is very old, 4.0 is the standard now.

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
