### ISSUE TITLE
Low-level Interface error when using DmassUmass_INPUTS

### ISSUE THREAD

**Issue by cedricgould** [CoolProp/CoolProp#1965]
Please excuse my first GitHub Issue report...

### Description

Using CoolProp to provide fluid thermodynamic property data to simple Nitrogen tank blow-down model.  Model equations of state track Conservations of Mass and Energy (Enthalpy -> Internal Energy form).  Differential equation solver integrates tank fluid total internal energy, while the CoolProp low-level interface is requested to update based on mass density and specific internal energy.  During the course of a simulation, the following traceback error occurs:

  File "\Documents\fluidprops\FluidProps.py", line 152, in update
    AS.update(CoolProp.DmassUmass_INPUTS, rho, u)

  File "CoolProp\AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update

  File "CoolProp\AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update

ValueError: Zero occurred in row 1, the matrix is singular. 

The last echoed tank condition prior to this error being thrown is:
Mass Density: 313.305125 kg/m3
Specific Internal Energy: 154834.285193 J/kg

### Steps to Reproduce

within Spyder IDE (4.1.3):

1. import CoolProp
2. AS = CoolProp.AbstractState("HEOS","nitrogen")
3. rho = 313.305125
4. u = 154834.285193
5. AS.update(CoolProp.DmassUmass_INPUTS, rho, u)

**Expected behavior:**
No error. The ability to call "AS.T()" and get Nitrogen temperature, in Kelvin

**Actual behavior:** [What actually happens]

Spyder consolde returns:

Traceback (most recent call last):

  File "<ipython-input-23-2c3f11f50064>", line 1, in <module>
    AS.update(CoolProp.DmassUmass_INPUTS, rho, u)

  File "CoolProp\AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update

  File "CoolProp\AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update

ValueError: Zero occurred in row 1, the matrix is singular. 

### Versions

**CoolProp Version:** 6.4.1  
**Operating System and Version:** Windows 10 Enterprise, 10.0.18362
**Access Method:** Python 3.7.6

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![image](https://user-images.githubusercontent.com/69771136/90344566-b2d8d300-dfcf-11ea-8e48-94c8f7907ba4.png)

**Comment by jowr** [comment]
As an intermediate fix, you could use a guess value to help the solver since you are running a continuous integration.

Start from a known state and keep calling  `update_with_guesses(self, input_pairs ipair, double Value1, double Value2, PyGuessesStructure guesses)`. This might help making your code more robust.

**Comment by cedricgould** [comment]
Thank you @jowr for the suggestion.  Unfortunately, I have been unable to provide my PyGuessesStructure with previous integration step solution.  Are there any examples in the Python language of making use of update_with_guesses functionality?

**Comment by jowr** [comment]
```Python
input_pair = CoolProp.DmassUmass_INPUTS
# First call, no guesses, should not fail
state.update(input_pair, rho_start, u_start)
# trace a line
for i in range(N):
    guesses.rhomolar = state.rhomolar()
    guesses.T = state.T()
    state.update_with_guesses(input_pair, rho[i], u[i], guesses)

**Comment by jowr** [comment]
with `guesses = CoolProp.CoolProp.PyGuessesStructure()`

**Comment by cedricgould** [comment]
Do the "guesses" need to be the same state variables as the "input_pair"?  I ask because your previous example shows "DmassUmass_INPUTS", but your "update_with_guesses" method call is providing guesses in terms of molar density and temperature.  Thanks again for your help, @jowr!

**Comment by cedricgould** [comment]
New problem: I've made the update suggested by @jowr, but apparently the fluid property combination I'm trying to calculate by (mass density and mass specific internal energy) is not yet supported by the method AbstractState.update_with_guesses:
![image](https://user-images.githubusercontent.com/69771136/91361897-1fad5380-e7ae-11ea-988d-0cc766529d20.png)
In addition, the error thrown indicates DmolarUmolar_INPUTS instead of what was, in fact, used: DmassUmass_INPUTS (see second line in screenshot above.  It appears as though I may be out of luck, or will need to re-convert the desired input quantities.  Is there any documentation to state which state variables are supported by update_with_guesses?

**Comment by jowr** [comment]
Guesses should always be rhom,olar and T - the EoS is explicit for those inputs. Sorry, there is no documentation for this case, we always considered the update_with_guesses calls as an internal function.

**Comment by cedricgould** [comment]
Update: I've changed the parameters provided to the guesses PyGuessesStructure object to molar density and temperature of the previous time step as suggested by @jowr, while leaving the input_pair as DmassUmass_INPUTS and providing mass density and mass specific internal energy to the .update_with_guesses method to no avail.  CoolProp still seems to think that "This pair of inputs [DmolarUmolar_INPUTS] is not yet supported" when I'm not using them.
![image](https://user-images.githubusercontent.com/69771136/91516144-96764980-e89f-11ea-9bc3-57f07711bdee.png)

**Comment by jowr** [comment]
The problem is that CoolProp converts all inputs to molar quantities before it starts the calculation. There are no calculation routines for mass-based inputs, only for molar inputs.

**Comment by ibell** [comment]
@jowr is right. Mass-based inputs are first converted to molar quantities, which is lossless.  Guesses are only fully used in some cases, the ones that were important to me when I added the functionality.  You are welcome to make a pull request adding the desired functionality.

**Comment by ibell** [comment]
Fixed by #2995
