### ISSUE TITLE
The molar density is below the minimum of 0.000000 mol/m3

### ISSUE THREAD

**Issue by Shihabus-Sakib-Rad** [CoolProp/CoolProp#2046]
### Description
Sometimes, Calculation with enthalpy and entropy is not possible. The following error is shown.
ValueError: The molar density of <> mol/m3 is below the minimum of 0.000000 mol/m3

### Steps to Reproduce

```python
from CoolProp.CoolProp import PropsSI

h = PropsSI("H", "T", 276, "P", 202650, "water")
s = PropsSI("S", "T", 276, "P", 202650, "water")
print(h, s)

# Now perform a reverse calculation with h and s
T = PropsSI("T", "H", h, "S", s, "water")
print(T)
```

**Expected behavior:** 
>12175.17443563349 43.603468459829365
276

**Actual behavior:**
>12175.17443563349 43.603468459829365
>Traceback (most recent call last):
  File "coolprop_test.py", line 7, in <module>
    T = PropsSI("T", "H", h, "S", s, "water")
  File "CoolProp\CoolProp.pyx", line 377, in CoolProp.CoolProp.PropsSI
  File "CoolProp\CoolProp.pyx", line 457, in CoolProp.CoolProp.PropsSI
  File "CoolProp\CoolProp.pyx", line 344, in CoolProp.CoolProp.__Props_err2

ValueError: The molar density of -303193.511710 mol/m3 is below the minimum of 0.000000 mol/m3 : PropsSI("T","H",12175.17444,"S",43.60346846,"water")

### Versions

**CoolProp Version:** 6.4.1
**Operating System and Version:** Windows 10
**Access Method:** python

**Comment by henningjp** [comment]
Your temperature is just 3°C above freezing at atmospheric pressure and your pressure is basically 2 atm.  The freezing line is an almost vertical line with pressure vs. temperature, but drifts just slightly to the right (warmer) as you go up in pressure.  I suspect that the iterative method used to solve with inputs of H and S is having trouble very near the freezing line.  Your example works just fine at >4°C at atmospheric pressure (101325 Pa) and >5°C at 2 atm (202650 Pa).

**Comment by henningjp** [comment]
@Shihabus-Sakib-Rad   I see your "thumbs up" on my response. Can this issue be closed?

**Comment by ibell** [comment]
Fixed by #2999
