### ISSUE TITLE
Missing binary pair for SO2 / H2O

### ISSUE THREAD

**Issue by andr1976** [CoolProp/CoolProp#2082]
Missing binary pair for water and SO2 raises exception 

Code 

```
from CoolProp.CoolProp import AbstractState
import CoolProp.CoolProp as CP

# Oxyfuel
mix1_comp = "CO2&H2O&N2&O2&Ar&CO&CH4&H2S&SO2"
mix1_x = [0.926295,1500e-6,0.02,0.03,0.02,1500e-6,500e-6,100e-6,100e-6]

HEOS = AbstractState('HEOS',mix1_comp)
HEOS.set_mole_fractions(mix1_x)
```

Traceback (most recent call last):
  File "\\ramoil.ramboll-group.global.network\Common\GlobalProjects\2015\1100019239\P-Process\CCS\CO2\CO2 VLE\pipeline_spec_comparison.py", line 9, in <module>
    HEOS = AbstractState('HEOS',mix1_comp)
  File "CoolProp\AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Could not match the binary pair [7446-09-5,7732-18-5] - for now this is an error.
### Description

**CoolProp Version:** 6.4.1
**Operating System and Version:**Win 10 x64
**Access Method:** Python 3.8

**Comment by ibell** [comment]
You could put in a placeholder model as described in the docs.

**Comment by andr1976** [comment]
Thanks for the advice, it seems many pairs with SO2 is missing. However as I try and add them suddenly known pairs starts complaining. 

´´´
from CoolProp.CoolProp import AbstractState
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt
import numpy as np 

# Oxyfuel
mix1_comp = "CO2&Water&N2&O2&Ar&CO&CH4&H2S&SO2"
mix1_x = [0.926295,1500e-6,0.02,0.03,0.02,1500e-6,500e-6,100e-6,100e-6]
mix1_x = [i/sum(mix1_x) for i in mix1_x]
#'124-38-9','7732-18-5'

CP.set_config_bool(CP.OVERWRITE_BINARY_INTERACTION, True)
CP.apply_simple_mixing_rule('7446-09-5','7732-18-5', 'linear')

CP.set_mixture_binary_pair_data('7446-09-5','7732-18-5', 'betaT', 1.0)
CP.set_mixture_binary_pair_data('7446-09-5','7732-18-5', 'gammaT', 1.0)
CP.set_mixture_binary_pair_data('7446-09-5','7732-18-5', 'betaV', 1.0)
CP.set_mixture_binary_pair_data('7446-09-5','7732-18-5', 'gammaV', 1.0)
HEOS = AbstractState('HEOS',mix1_comp)
#PR = AbstractState('SRK',mix1_comp)
´´´
Traceback (most recent call last):
  File "\\ramoil.ramboll-group.global.network\Common\GlobalProjects\2015\1100019239\P-Process\CCS\CO2\CO2 VLE\pipeline_spec_comparison.py", line 27, in <module>
    HEOS = AbstractState('HEOS',mix1_comp)
  File "CoolProp\AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Could not match the binary pair [124-38-9,7727-37-9] - for now this is an error.

I must be doing something wrong

**Comment by ibell** [comment]
I think starting simple is the way to go.  Binary mixtures, or maybe ternaries.  There are interoperability scripts that allow you to go backwards and forwards between REFPROP and CoolProp formats: https://github.com/ianhbell/REFPROP-interop

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
