### ISSUE TITLE
Failing pQ saturation calls near the critical point

### ISSUE THREAD

**Issue by EduBic** [CoolProp/CoolProp#2169]
Hello

I wanted to plot the saturation curves for R134a refrigerant in the p-H plane.
Given a range of pressures (p) i compute the entalphy of saturated liquid (q = 0) and gas (q = 1) with the following function call:
`PropsSI("H", "P", p, "Q", q, "R134a")`

### Actual behavior

Near the critical point the curve appears strange. The plot is explicative:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/13170564/191515942-a22b9b70-0fc8-4ca4-9989-53951cf7264e.png)

I did the same in excel, the plot has the same strange thing on the top.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/13170564/191516965-8f021948-bf64-4ba0-9f92-0db8a9bfdf12.png)

### Expected behavior

For curiosity I tried with an old Version (8.0.0) of RefrProp and it's what I expect:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/13170564/191516029-2c63fbba-8167-49b7-89d4-7766b3774339.png)

### Versions

**CoolProp Version:** 6.4.1 and Nightly
**Operating System and Version:** Windows 7 - 10
**Access Method:** C# wrapper with Interop & Excel

Thanks

**Comment by Padanian** [comment]
I can confirm I've got the same issue, and not just with R134a. Around the critical point calculation diverges.

**Comment by GiuSirianni** [comment]
Hello everyone.

First of all, thank you for your work on CoolProp! I'm sorry for adding to an old issue, but  I don't think it merits opening a new issueas I'll probably be adding nothing new to what has already been said.

I imagine the issue lies in the choice of the initial guess for the PT solver. A minimum working script in python for MM:

```python
import CoolProp  
 
AS = CoolProp.AbstractState("HEOS", "MM") 

# close to critical
P = 1938804.1000000000931 
 
AS.update(CoolProp.PQ_INPUTS, P, 1.0) 
print("WORKS!")
print("rho1 = " + str(AS.rhomass()))
print("p1   = " + str(AS.p()))
print("T1   = " + str(AS.T())) 
 
# slightly further from critical
P = P*0.9999999
 
AS.update(CoolProp.PQ_INPUTS, P, 1.0) 
print("NO WORKS!") 
```

The output:

```console
python3 main.py
WORKS!
rho1 = 322.25830443481016
p1   = 1938804.0999999805
T1   = 518.749999
Traceback (most recent call last):
  File "/mnt/e/publications/2024_phase_transition/_simulations/validation_relaxation/thermochemical/complete/mm_nozzle/_postprocess/main.py", line 17, in <module>
    AS.update(CoolProp.PQ_INPUTS, P, 1.0)
  File "CoolProp/AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp/AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update
ValueError: solver_rho_Tp was unable to find a solution for T=   516.832, p=1.9388e+06, with guess value    1556.05 with error: Householder4 reached maximum number of iterations
```

An identical code in our in-house CFD code implementation of CoolProp (we nee to save an approximation of the saturation curve for performance reasons):

```console
> Maximum pressure = 1938804.1000000000931 [Pa]  (Critical pressure = 1939000 [Pa])
 > Maximum pressure = 1938803.9061195901595 [Pa]  (Critical pressure = 1939000 [Pa])
terminate called after throwing an instance of 'CoolProp::CoolPropError<(CoolProp::CoolPropBaseError::ErrCode)4>'
  what():  solver_rho_Tp was unable to find a solution for T=   516.832, p=1.9388e+06, with guess value    1556.05 with error: Householder4 reached maximum number of iterations
```

**Comment by ibell** [comment]
You might be interested in these superancillary equations, they should replace your in-house solution: https://doi.org/10.1063/5.0191228

**Comment by GiuSirianni** [comment]
Oh sorry, maybe I didn't explain thoroughly: what I meant by "an identical code snippet" is that we have an identical snippet to the python one above that causes the same issue. 

Thank you for the paper reccomendation, we will most likely implement these!
