### ISSUE TITLE
[Gasmix]Viscosity model is not available for this fluid

### ISSUE THREAD

**Issue by Dennis-89** [CoolProp/CoolProp#2180]
Hello,

I'm trying to calculate some gas-properties, but I always run into an Value Error.
For example I want the viscosity of the following gas-mix: 57% H2, 21% CO and 22% CH4.

I used this Code:
`import CoolProp

class Gas:
    def __init__(self, gas_name, gas_percent, temperature, pressure):
        self.temperature = temperature + 273.15
        self.pressure = pressure * 10**5
        # HEOS is the used backend
        self._gas = CoolProp.CoolProp.AbstractState('HEOS', gas_name)
        self._gas.specify_phase(CoolProp.iphase_gas)
        self._gas.set_mole_fractions(gas_percent)
        self._gas.update(CoolProp.PT_INPUTS, self.pressure, self.temperature)

    @property
    def dynamic_viscosity(self):
        return self._gas.viscosity()

def main():
    gas = Gas('H2&CO&CH4', (0.57, 0.21, 0.22), 10, 1)
    print(gas.dynamic_viscosity)

if __name__ == '__main__':
    main()`

I get this Error:
`Traceback (most recent call last):
  File "C:\Users\straub\AppData\Roaming\JetBrains\PyCharmCE2022.1\scratches\scratch_1.py", line 25, in <module>
    main()
  File "C:\Users\straub\AppData\Roaming\JetBrains\PyCharmCE2022.1\scratches\scratch_1.py", line 21, in main
    print(gas.dynamic_viscosity)
  File "C:\Users\straub\AppData\Roaming\JetBrains\PyCharmCE2022.1\scratches\scratch_1.py", line 16, in dynamic_viscosity
    return self._gas.viscosity()
  File "CoolProp\AbstractState.pyx", line 321, in CoolProp.CoolProp.AbstractState.viscosity
  File "CoolProp\AbstractState.pyx", line 323, in CoolProp.CoolProp.AbstractState.viscosity
ValueError: Viscosity model is not available for this fluid

Process finished with exit code 1
`

**CoolProp Version:** 
`CoolProp.__version__
'6.4.1'`
**Operating System and Version:** Windows 10 / Fedora 34 (both with the same issus)
**Access Method:** Python 3.10

Can anyone explain this behavior? Is it a backend-problem/bug?
Actually I have to test if CoolProp is the libary I coul use for my project, so at this moment I can't buy the REPROP-backend. Is there anything for free, to calculate this and other gas-mix?

Thank you and Greetings!

**Comment by ibell** [comment]
Cantera can do viscosity calculations I believe.

The viscosity routines in CoolProp are very rudimentary and I should have
not put them in.  Use the routines in REFPROP, or perhaps an entropy
scaling approach like this one:
https://link.springer.com/article/10.1007/s10765-022-03096-9
