### ISSUE TITLE
REFPROP v10.0 and PFHLSH error 3

### ISSUE THREAD

**Issue by cresus** [CoolProp/CoolProp#2183]
Hello,

I'm using the coolprop front end with refprop and just ran into this error.  I have no problem with this function call when at lower pressures, but here I get an issue.  For reference, if I use the refprop GUI it has no issue with this.  Has anyone seen this problem?

ValueError: HmolarPmolar: [PHFLSH error 3] One or more inputs are out of range; Temperature below triple-point or minimum temperature: T = 22.4391 K, Tmin = 67.1408 K; Density above upper limit: D = 82.5965 mol/L, Dmax = 46.2262 mol/L.                                              : PropsSI("T","P",55000000,"H",1056271.093,"REFPROP::H2[0.26200]&CO2[0.25700]&CO[0.48100]")

I have CoolProp 6.4.1 installed and am running this on Windows 10 in Python 3.9.12.  

When called through coolprop as above, I get this error about temperature being below triple-point.  However, in the Refprop GUI for this mixture it has no problem.  Is there a workaround to this?

<img width="412" alt="Capture" src="https://user-images.githubusercontent.com/28229360/200035065-b6e1f4b2-d89f-4983-ba34-3bab3455a9f7.PNG">

**Comment by ibell** [comment]
See faq number 1: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by ibell** [comment]
You need to make sure you use the same reference states everywhere

**Comment by cresus** [comment]
Thanks.  I don't think that's the problem though.  Like I said, it works with slightly lower pressures with no fault and matches exactly (so not obviously a reference state problem).  

![image](https://user-images.githubusercontent.com/28229360/200092499-08e37349-1cdc-4716-98f4-ede10aacf08b.png)

**Comment by ibell** [comment]
Same exact density obtained?

**Comment by cresus** [comment]
Yes.  For this P and H, using the calls I match exactly.

![image](https://user-images.githubusercontent.com/28229360/200093044-fc6afb3b-0a0b-4cb4-a692-f2bae646091b.png)

Thanks for looking.

**Comment by ibell** [comment]
So it's not a reference state problem. Can you use the low level
interface?  If so building the phase envelope could help.

**Comment by cresus** [comment]
Took me a few minutes to figure out how to work the low level.  Same problem there when trying to call that specific one.  When you said phase envelope, do you mean trying to recreate something like this?  REFPROP has it pretty well behaved in the area I'm looking.

![image](https://user-images.githubusercontent.com/28229360/200094719-bd78e139-6147-4727-a4dc-1c68917459e9.png)


```
REFPROP = CP.AbstractState("REFPROP", "H2&CO2&CO")
REFPROP.set_mole_fractions([0.262, 0.257, 0.481])
REFPROP.update(CP.HmassP_INPUTS, 1000000, 45000000)
REFPROP.t()
Traceback (most recent call last):
  File "C:\Users\scapu\.conda\envs\ct-env\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-3db4aafd72b7>", line 1, in <cell line: 1>
    REFPROP.t()
AttributeError: 'CoolProp.CoolProp.AbstractState' object has no attribute 't'
REFPROP.rhomass()
Out[20]: 179.52328090900627
REFPROP.T()
Out[21]: 646.0660214622908
REFPROP.update(CP.HmassP_INPUTS, 1000000, 55000000)
Traceback (most recent call last):
  File "C:\Users\scapu\.conda\envs\ct-env\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-7c0b87bb7e2c>", line 1, in <cell line: 1>
    REFPROP.update(CP.HmassP_INPUTS, 1000000, 55000000)
  File "CoolProp\AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
```

**Comment by ibell** [comment]
Call the build_phase_envelope method after instantiating

**Comment by cresus** [comment]
That worked.  So solution is to convert my code to use the low level interface and build the phase envelope.  Thanks for your help!
