### ISSUE TITLE
Problem with Neopentane in mixture

### ISSUE THREAD

**Issue by lorenz-ptb** [CoolProp/CoolProp#2344]
### Description

Using "Neopentane" in self-defined mixtures with PropSI (to query the molar mass) results in a Value. Using "Neopentane" as pure gas works though.

### Steps to Reproduce

1. 
```python
import CoolProp.CoolProp as CP

CP.PropsSI("M", "Neopentane[0.5]&n-Hexane[0.5]")
```
2. 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\\CoolProp.pyx", line 391, in CoolProp.CoolProp.PropsSI
  File "CoolProp\\CoolProp.pyx", line 405, in CoolProp.CoolProp.PropsSI
  File "CoolProp\\CoolProp.pyx", line 351, in CoolProp.CoolProp.__Props_err1
ValueError: Neither input to Props1SI [Neopentane[0.5]&n-Hexane[0.5],M] is a valid fluid :: inputs were :"M","Neopentane[0.5]&n-Hexane[0.5]"
```

**Expected behavior:** I expect to get the molar mass for a mixture of 1:1 neopentane:n-hexane.

**Actual behavior:** Python raises ValueError.

### Versions

**CoolProp Version:** CoolProp 6.6.0 
**Operating System and Version:** Windows 10  
**Access Method:** Python 3.11.4 

### Additional Information

Using "Neopentane" alone works as expected: CP.PropsSI("M", "Neopentane") -> 0.07214878
Even in combination with "Methane" it works: CP.PropsSI("M", "Neopentane[0.5]&Methane[0.5]") -> 0.044095789999999996
When adding another component or in combination with other gases, the ValueError appears.

**Comment by ibell** [comment]
The problem is that there are no mixing parameters available for this mixture. In the low-level interface you get a more helpful error message. With
```python
import CoolProp.CoolProp as CP 
AS = CP.AbstractState('HEOS','Neopentane&n-Hexane')
```
I get
```
File "CoolProp\\AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__  
ValueError: Could not match the binary pair [110-54-3,463-82-1] - for now this is an error.
```

**Comment by ibell** [comment]
Closing as part of an issue-tracker cleanup — this issue has had no activity in over two years.

*To be transparent: this comment and the close action are being performed by Claude (Anthropic's AI coding assistant), running on behalf of @ibell. Ian reviewed and approved the bulk-close criteria; I am the one executing the action.*

If you would like this issue reconsidered, please feel free to **re-open it** — a fresh comment with current behaviour against the latest CoolProp release is the most useful way to revive the discussion.

— Claude (acting for @ibell)
