### ISSUE TITLE
CoolProp online vapor quality issue for water fluid

### ISSUE THREAD

**Issue by mprogram** [CoolProp/CoolProp#2359]
I encountered an error while using the online version of the software (https://ibell.pythonanywhere.com/). 

The error occurs when I try to calculate properties for the fluid “water” under a pressure of 101325 Pa and a vapour quality that is not 0 or 1. I have tried using both comma and dot separation (like 0.1 and 0,1), but the error persists.

The error code is: "Internal error

A ticket has been issued for this error: coolpropgit/5.248.152.247.2024-03-20.21-23-30.20d4ce59-0901-4e2e-8f55-73ae5e5f495e"
![Screenshot_20240320_232339](https://github.com/CoolProp/CoolProp/assets/13729841/0b58eb29-b53d-4f92-b747-aaefd0b9476a)
![Screenshot_20240320_232320](https://github.com/CoolProp/CoolProp/assets/13729841/1d90d913-e02e-4c66-b1b9-531d1167c72a)

**Comment by mprogram** [comment]
Issue is similar to https://github.com/CoolProp/CoolProp/issues/2219

**Comment by ibell** [comment]
Aha here is the bug from the error report:

Traceback (most recent call last):
  File "/home/ibell/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/ibell/web2py/applications/coolpropgit/controllers/default.py"
<https://ibell.pythonanywhere.com/admin/edit/coolpropgit/controllers/default.py>,
line 158, in <module>
  File "/home/ibell/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/home/ibell/web2py/applications/coolpropgit/controllers/default.py"
<https://ibell.pythonanywhere.com/admin/edit/coolpropgit/controllers/default.py>,
line 76, in next
    TR("Speed of sound [m/s]", HEOS.speed_sound())
  File "CoolProp/AbstractState.pyx", line 309, in
CoolProp.CoolProp.AbstractState.speed_sound
  File "CoolProp/AbstractState.pyx", line 311, in
CoolProp.CoolProp.AbstractState.speed_sound
ValueError: Speed of sound is not defined for two-phase states because
it depends on the distribution of phases.


That makes sense. I fixed it once I knew what the problem is.
