### ISSUE TITLE
Refprop viscosity not working 404A

### ISSUE THREAD

**Issue by mayersre** [CoolProp/CoolProp#433]
``` python
print('Coolprop Version : ',CoolProp.__version__)
Coolprop Version :  5.0.7dev
print('Gitrevision      : ',CoolProp.__gitrevision__)
Gitrevision      :  3102ec9656d7d84f94f66fe9471cc98ce62b3ef4

PropsSI('V','P',101325,'T',293.15, 'R404A')
1.2017631965942629e-05
```
Same call to Refprop causes ValueError, no matter if mixture file or mixture string
``` python
PropsSI('V','P',101325,'T',293.15, 'REFPROP::R404A')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 204, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:16591)
  File "CoolProp\CoolProp.pyx", line 278, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:16394)
  File "CoolProp\CoolProp.pyx", line 173, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:14935)
ValueError: [TRNPRP error 40] transport equations are not available for one or more of the fluids : PropsSI("V","P",101325,"T",293.15,"REFPROP::R404A")
```
```
PropsSI('V','P',101325,'T',293.15, 'REFPROP::R125[0.357816784026318]&R143a[0.357816784026318]&R134a[0.357816784026318]')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 204, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:16591)
  File "CoolProp\CoolProp.pyx", line 278, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:16394)
  File "CoolProp\CoolProp.pyx", line 173, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:14935)
ValueError: PT: [TPFLSH error  8] one or more inputs are out of range:     composition(s) out of range, Xsum = 1.0734503521 mol frac, X(i) = 0.3578167840 0.3578167840 0.3578167840                           : PropsSI("V","P",101325,"T",293.15,"REFPROP::R125[0.357816784026318]&R143a[0.357816784026318]&R134a[0.357816784026318]")
```

**Comment by ibell** [comment]
Two problems here...

A) REFPROP's implementation of the pseudo-pure fluids ("REFPROP::R404A") does not include any transport properties.  Hence the error.

B) Your call with the mixture is invalid because the mole fractions do not sum to one, as explained in the error message
