### ISSUE TITLE
Allow mixtures to have zero mole fractions

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#452]

**Comment by ibell** [comment]
These should be the same
``` python
import CoolProp

print CoolProp.CoolProp.PropsSI('T','P',201325,'Q',0,'HEOS::Water[0.5]&Nitrogen[0.5]')
print CoolProp.CoolProp.PropsSI('T','P',201325,'Q',0,'HEOS::Water[0.5]&Nitrogen[0.5]&Argon[0.0]&CO2[0.0]')
```
but you get
```
90.895353356
Traceback (most recent call last):
  File "trash15.py", line 4, in <module>
    print CoolProp.CoolProp.PropsSI('T','P',201325,'Q',0,'HEOS::Water[0.5]&Nitrogen[0.5]&Argon[0.0]&CO2[0.0]')
  File "CoolProp.pyx", line 204, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:16127)
  File "CoolProp.pyx", line 284, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:15930)
  File "CoolProp.pyx", line 173, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:14348)
ValueError: solver_rho_Tp was unable to find a solution for T=    91.271, p=    201325, with guess value    59057.9 : PropsSI("T","P",201325,"Q",0,"HEOS::Water[0.5]&Nitrogen[0.5]&Argon[0.0]&CO2[0.0]")
```
instead
