### ISSUE TITLE
CoolProp 5.0.8 from PyPI: Python import error

### ISSUE THREAD

**Issue by jessejohns** [CoolProp/CoolProp#592]
Just installed version 5.0.8 with python version 2.7.6 and python 3.4.0:

I receive the following errors, for both, respectively:
``` ```
>>> import CoolProp.CoolProp as CP 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/__init__.py", line 5, in <module>
    from . import constants
  File "CoolProp/constants.py", line 5, in <module>
    from . import _constants
ImportError: cannot import name _constants
```
``` ```
>>> import CoolProp.CoolProp as CP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jesse/Source/CoolProp-5.0.8/CoolProp/__init__.py", line 5, in <module>
    from . import constants
  File "/home/jesse/Source/CoolProp-5.0.8/CoolProp/constants.py", line 5, in <module>
    from . import _constants
ImportError: cannot import name '_constants'

```
**EDIT:** I am running Linux Mint 17

**Comment by jessejohns** [comment]
I created symbolic libraries into the wrong directory.

**Comment by ibell** [comment]
Glad to hear you got it sorted.
