### ISSUE TITLE
Can't set the State of a refrigerant using Quality

### ISSUE THREAD

**Issue by romarro** [CoolProp/CoolProp#676]
Hi when I try to use the Quality for setting the state of the fluid I get an error described below:
Imported NumPy 1.9.2, SciPy 0.15.1, Matplotlib 1.4.3, CoolProp 5.0.8, Pint 0.6
+ guidata 1.6.2, guiqwt 2.3.2
Type "scientific" for more details.
>>> from CoolProp.CoolProp import State
>>> st2=State('R134a',dict(P=1620.0,Q=1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 500, in CoolProp.CoolProp.State.__init__ (CoolProp\CoolProp.cpp:21564)
  File "CoolProp\CoolProp.pyx", line 588, in CoolProp.CoolProp.State.update (CoolProp\CoolProp.cpp:22842)
  File "CoolProp\CoolProp.pyx", line 422, in CoolProp.CoolProp.toSI (CoolProp\CoolProp.cpp:21248)
KeyError: 'key is invalid to toSI'

I want to get the density for a saturated gas using the State class in python

**Comment by jowr** [comment]
Hi, the `State` object is deprecated. Please use the `AbstractState`, see also: http://coolprop.sourceforge.net/coolprop/LowLevelAPI.html#partial-derivatives for an example in Python.

**Comment by ibell** [comment]
@jowr is right, State class is still there for some projects that need it, but there are no plans to update it, and you should use AbstractState in its place.
