### ISSUE TITLE
Mix call failure after release update

### ISSUE THREAD

**Issue by mayersre** [CoolProp/CoolProp#681]
Hi,
my mixture plots work fine with
5.1.0
1a279124004ddc778c3fbab29fbb5997c54b9054

after update I get this :

5.1.1dev
99af9d6434538bf52fc8560e3bb8fb2e3b3f2fa9

Imports done
 __main__ : Checking for file : 
 __main__ : No file, main started
Init started at : 2015-05-22 09:34:48.513086
Refrigerant :  R-448A  /  REFPROP::R32[0.4312182019885588]&R125[0.1869141314819922]&R1234yf[0.1513192564858993]&R134a[0.1775866736172168]&R1234ze[0.0529617364263329]
Debug flag set to  False
Traceback (most recent call last):
  File "/home/mayers/git/bfstools/phdiagramm_v60.py", line 3314, in <module>
    PH_R448A()
  File "/home/mayers/git/bfstools/phdiagramm_v60.py", line 2895, in PH_R448A
    myrp=phdia_rp(ref=R448A,refname='R-448A',Tmin=213.15,Isentropenabstand=0.02)
  File "/home/mayers/git/bfstools/phdiagramm_v60.py", line 204, in __init__
    self.hmin=PropsSI('H','P',self.pmin,'Q',0,self.ref)-10+self.ch
  File "CoolProp/CoolProp.pyx", line 216, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:25064)
  File "CoolProp/CoolProp.pyx", line 296, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:24865)
  File "CoolProp/CoolProp.pyx", line 187, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:23256)
ValueError: PropsSI failed ungracefully :: inputs were:"H","P",5.0000000000000000e+04,"Q",0.0000000000000000e+00,"REFPROP::R32[0.4312182019885588]&R125[0.1869141314819922]&R1234yf[0.1513192564858993]&R134a[0.1775866736172168]&R1234ze[0.0529617364263329]"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

**Comment by mayersre** [comment]
After the fix it works again now like usual, thanks
