### ISSUE TITLE
ValueError: p is not a valid number

### ISSUE THREAD

**Issue by denfromufa** [CoolProp/CoolProp#924]
```
rp=CP.AbstractState('HEOS','Methane&Water')
rp.set_mole_fractions([0.529,0.471])
p1=3.0e7
t1=273.15+50
p2=1.0e7
rp.update(CP.PT_INPUTS,p1,t1)
h1=rp.hmass()
h1
```
and the traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-114-a3bda4f261c5> in <module>()
      2 t1=273.15+50
      3 p2=1.0e7
----> 4 rp.update(CP.PT_INPUTS,p1,t1)
      5 h1=rp.hmass()
      6 h1

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:11402)()

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:11291)()

ValueError: p is not a valid number
```

**Comment by ibell** [comment]
How about building a phase envelope first?

**Comment by denfromufa** [comment]
this was not required for REFPROP engine, why is it requires for HEOS?

**Comment by ibell** [comment]
Basically because flash routine for mixtures are hard.  Really hard.  REFPROP has better routines because they have been working on it for years.  REFPROP will likely always be better on this front.

**Comment by ibell** [comment]
So here's the thing.  Unless you have an error in your inputs, there is no way your inputs will work.  The dewpoint temperature at 3e7 Pa is 580.346698779 K.  See the below phase envelope, generated with this code:

```
import CoolProp.CoolProp as CP, matplotlib.pyplot as plt

rp=CP.AbstractState('HEOS','Methane&Water')
rp.set_mole_fractions([0.529,0.471])
p1=3.0e7
rp.update(CP.PQ_INPUTS,p1,1)
print rp.T()

rp.build_phase_envelope("")
pe = rp.get_phase_envelope_data()


plt.plot(pe.T, pe.p)
plt.yscale('log')
plt.xlabel('T (K)')
plt.ylabel('p (Pa)')
plt.xlim(0, 800)
plt.ylim(0, 80e7)
plt.savefig('MethWaterPE.png')
```
![methwaterpe](https://cloud.githubusercontent.com/assets/1859947/12376033/ec0e885a-bc9c-11e5-9034-aa3e5cb99455.png)

**Comment by denfromufa** [comment]
i don't see any point in showing phase envelope. i just need to flash from one state to another without worrying about phases.

**Comment by ibell** [comment]
And if you switch to REFPROP backend, it also doesn't work:
``` python
import CoolProp.CoolProp as CP

rp=CP.AbstractState('REFPROP','Methane&Water')
rp.set_mole_fractions([0.529,0.471])
p1=3.0e7
t1=273.15+50
p2=1.0e7
rp.update(CP.PT_INPUTS,p1,t1)
h1=rp.hmass()
h1
```
yields
```
Traceback (most recent call last):
  File "C:\Users\Belli\Desktop\doo.py", line 8, in <module>
    rp.update(CP.PT_INPUTS,p1,t1)
  File "CoolProp\AbstractState.pyx", line 70, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:12489)
  File "CoolProp\AbstractState.pyx", line 72, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:12375)
ValueError: PT: [TPFLSH error 211] bubble point calculation did not converge:  [SATT error 128] iteration for saturation state did not converge; T =  323.15 K.
```
