### ISSUE TITLE
ValueError: Bad phase to solver_rho_Tp_SRK (CoolProp 5.1.2)

### ISSUE THREAD

**Issue by Heathckliff** [CoolProp/CoolProp#933]
Fluid = 'air'
EOS = CoolProp.AbstractState('HEOS', Fluid)
EOS.update(CoolProp.PT_INPUTS,4.0e6,300)

Traceback (most recent call last):
  File "<ipython-input-89-8c80d33865e6>", line 1, in <module>
    EOS.update(CoolProp.PT_INPUTS,4.0e6,300)

  File "CoolProp\AbstractState.pyx", line 70, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:11402)

  File "CoolProp\AbstractState.pyx", line 72, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:11291)

ValueError: Bad phase to solver_rho_Tp_SRK

**Comment by ibell** [comment]
I'll take a look and see what is going on.  Should be simple to fix.

**Comment by ibell** [comment]
closed by 4f4344e3ef965c1d9dfd707c3f88738463741c0e
